import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {ChessGame,chooseComputerMove} from './engine.js';
const $=s=>document.querySelector(s),sceneEl=$('#scene'),logEl=$('#log'),turnEl=$('#turn'),stateEl=$('#state'),game=new ChessGame();
const themes={classic:{light:0xd7c7a3,dark:0x4b3425,w:0xf4eee2,b:0x232831,glow:0xfbbf24},arcane:{light:0x28465d,dark:0x111c3c,w:0x7dd3fc,b:0xa78bfa,glow:0x67e8f9},monsters:{light:0x536b43,dark:0x253422,w:0xc7f9a9,b:0x7b3248,glow:0xb7ff62},brick:{light:0xb8b8aa,dark:0x39465a,w:0xe5e7eb,b:0xdc3d3d,glow:0xfbbf24},cosmic:{light:0x273552,dark:0x090b20,w:0x8be9fd,b:0xff79c6,glow:0x5eead4}};
let theme='classic',selected=null,legal=[],busy=false,soundOn=true,aiTimer=null,generation=0,toastTimer=null,scene,camera,renderer,orbit,boardGroup,pieceGroup,fxGroup;
const reducedMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;
function material(color,glow=0){return new THREE.MeshStandardMaterial({color,roughness:.4,metalness:theme==='cosmic'?.65:.16,emissive:glow,emissiveIntensity:.35})}
function makePiece(p,x,y){const root=new THREE.Group(),m=material(p.c==='w'?themes[theme].w:themes[theme].b),facet=theme==='brick'?8:24;
 const part=(geo,height)=>{const mesh=new THREE.Mesh(geo,m);mesh.position.y=height;mesh.castShadow=true;root.add(mesh);return mesh};
 part(new THREE.CylinderGeometry(.36,.44,.18,facet),.13);part(new THREE.CylinderGeometry(.27,.34,.15,facet),.27);
 const h=p.t==='p'?.44:p.t==='k'?1:.76;part(new THREE.CylinderGeometry(.16,.29,h,facet),.37+h/2);
 if(p.t==='p')part(new THREE.SphereGeometry(.24,facet,12),.82);
 if(p.t==='r'){part(new THREE.CylinderGeometry(.30,.23,.27,facet),1);for(let i=0;i<4;i++){const a=i*Math.PI/2,c=part(new THREE.BoxGeometry(.14,.17,.14),1.2);c.position.x=Math.cos(a)*.23;c.position.z=Math.sin(a)*.23}}
 if(p.t==='n'){const head=part(new THREE.ConeGeometry(.3,.63,theme==='brick'?5:12),1.04);head.rotation.z=.26}
 if(p.t==='b'){part(new THREE.SphereGeometry(.25,facet,12),1.08);part(new THREE.ConeGeometry(.14,.3,facet),1.34)}
 if(p.t==='q'){part(new THREE.SphereGeometry(.27,facet,12),1.2);for(let i=0;i<5;i++){const a=i*Math.PI*2/5,c=part(new THREE.SphereGeometry(.08,8,6),1.47);c.position.x=.25*Math.cos(a);c.position.z=.25*Math.sin(a)}}
 if(p.t==='k'){part(new THREE.SphereGeometry(.27,facet,12),1.37);part(new THREE.BoxGeometry(.11,.40,.11),1.69);part(new THREE.BoxGeometry(.36,.1,.11),1.73)}
 if(theme==='monsters')for(const side of[-1,1]){const horn=new THREE.Mesh(new THREE.ConeGeometry(.075,.35,8),material(p.c==='w'?0xe9ffc1:0xffb0c1));horn.position.set(side*.19,1.16,.03);horn.rotation.z=-side*.32;horn.castShadow=true;root.add(horn)}
 if(theme==='arcane'||theme==='cosmic'){const ring=new THREE.Mesh(new THREE.TorusGeometry(.33,.028,8,28),material(themes[theme].glow,themes[theme].glow));ring.position.y=.48;ring.rotation.x=Math.PI/2;root.add(ring)}
 if(theme==='brick')for(let i=0;i<4;i++){const a=i*Math.PI/2,stud=new THREE.Mesh(new THREE.CylinderGeometry(.065,.065,.05,10),m);stud.position.set(.18*Math.cos(a),.25,.18*Math.sin(a));root.add(stud)}
 root.position.set(x-3.5,.08,y-3.5);root.userData={piece:true,x,y};root.traverse(node=>node.userData.root=root);return root}
function clearGroup(group){while(group.children.length){const item=group.children[0];group.remove(item);item.traverse(node=>{node.geometry?.dispose();if(node.material)(Array.isArray(node.material)?node.material:[node.material]).forEach(m=>m.dispose())})}}
function createBoard(){clearGroup(boardGroup);const base=new THREE.Mesh(new THREE.BoxGeometry(9,.35,9),material(0x101820));base.position.y=-.25;base.receiveShadow=true;boardGroup.add(base);for(let y=0;y<8;y++)for(let x=0;x<8;x++){const sq=new THREE.Mesh(new THREE.BoxGeometry(.98,.12,.98),material((x+y)%2?themes[theme].dark:themes[theme].light));sq.position.set(x-3.5,0,y-3.5);sq.userData={square:true,x,y};sq.receiveShadow=true;boardGroup.add(sq)}}
function drawPieces(){clearGroup(pieceGroup);for(let y=0;y<8;y++)for(let x=0;x<8;x++)if(game.piece(x,y))pieceGroup.add(makePiece(game.piece(x,y),x,y));highlight()}
function highlight(){for(const o of boardGroup.children)if(o.userData.square){o.material.emissive.setHex(0);o.material.emissiveIntensity=.52;if(selected&&o.userData.x===selected.x&&o.userData.y===selected.y)o.material.emissive.setHex(0xfbbf24);const m=legal.find(m=>m.nx===o.userData.x&&m.ny===o.userData.y);if(m)o.material.emissive.setHex(game.piece(m.nx,m.ny)||game.ep?.x===m.nx&&game.ep?.y===m.ny?0xfb7185:0x2dd4bf)}}
function renderStatus(){const st=game.status();turnEl.textContent=(game.turn==='w'?'White':'Black')+' to move';stateEl.textContent=st.over?(st.winner?(st.winner==='w'?'White':'Black')+' wins · checkmate':'Draw · '+st.kind):(st.check?'CHECK':'Battle in progress');logEl.replaceChildren(...game.moves.map((move,i)=>{const li=document.createElement('li');li.textContent=(i%2===0?'White · ':'Black · ')+move.notation;return li}));logEl.scrollTop=logEl.scrollHeight;$('#difficulty').disabled=$('#mode').value!=='ai';if(st.over)clearTimeout(aiTimer)}
function notice(message){const t=$('#toast');t.textContent=message;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),2500)}
function sound(frequency=230){if(!soundOn)return;try{const audio=new (window.AudioContext||window.webkitAudioContext)(),osc=audio.createOscillator(),gain=audio.createGain();osc.type=theme==='cosmic'?'sine':'triangle';osc.frequency.value=frequency;gain.gain.setValueAtTime(.06,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.12);osc.connect(gain).connect(audio.destination);osc.start();osc.stop(audio.currentTime+.12);osc.onended=()=>audio.close()}catch{soundOn=false}}
function battleEffect(x,y){sound(theme==='cosmic'?400:160);if(reducedMotion)return Promise.resolve();const count=theme==='brick'?26:theme==='cosmic'?18:theme==='arcane'?20:12,particles=[];for(let i=0;i<count;i++){const geometry=theme==='brick'?new THREE.BoxGeometry(.14,.14,.14):theme==='arcane'?new THREE.TetrahedronGeometry(.08):new THREE.SphereGeometry(.055,6,4),p=new THREE.Mesh(geometry,material(themes[theme].glow,themes[theme].glow));p.position.set(x-3.5,.8,y-3.5);p.userData.velocity=new THREE.Vector3((Math.random()-.5)*.15,Math.random()*.11+.06,(Math.random()-.5)*.15);fxGroup.add(p);particles.push(p)}return new Promise(resolve=>{let frame=0;function animate(){frame++;for(const p of particles){p.position.add(p.userData.velocity);p.userData.velocity.y-=theme==='brick'?.006:.003;p.rotation.x+=.11;p.rotation.z+=.08;p.scale.multiplyScalar(.964)}if(frame<36)requestAnimationFrame(animate);else{clearGroup(fxGroup);resolve()}}animate()})}
function promotionChoice(){return new Promise(resolve=>{const modal=$('#promotion'),choices=$('#promotionChoices');choices.replaceChildren();const titles={q:'Queen',r:'Rook',b:'Bishop',n:'Knight'};for(const p of['q','r','b','n']){const b=document.createElement('button');b.textContent=titles[p];b.onclick=()=>{modal.classList.add('hidden');resolve(p)};choices.appendChild(b)}modal.classList.remove('hidden');choices.firstElementChild.focus()})}
async function applyMove(m,computer=false,promotion=null){if(busy||game.status().over)return false;const p=game.piece(m.x,m.y),target=game.piece(m.nx,m.ny),captured=!!(target||p?.t==='p'&&game.ep?.x===m.nx&&game.ep?.y===m.ny);if(!p||p.c!==game.turn)return false;if(!game.legalMoves(m.x,m.y).some(candidate=>candidate.nx===m.nx&&candidate.ny===m.ny))return false;busy=true;if(p.t==='p'&&(m.ny===0||m.ny===7)&&!promotion)promotion=computer?'q':await promotionChoice();const move=game.move(m.x,m.y,m.nx,m.ny,promotion||'q');if(!move){busy=false;return false}selected=null;legal=[];drawPieces();renderStatus();if(captured)await battleEffect(m.nx,m.ny);else sound(290);busy=false;if(!computer&&$('#mode').value==='ai'&&game.turn==='b'&&!game.status().over)queueComputer();return true}
function queueComputer(){clearTimeout(aiTimer);const ticket=++generation;aiTimer=setTimeout(async()=>{if(ticket!==generation||busy||game.turn!=='b'||$('#mode').value!=='ai'||game.status().over)return;const strength=Number($('#difficulty').value);stateEl.textContent='Computer thinking…';await new Promise(resolve=>requestAnimationFrame(resolve));if(ticket!==generation)return;const m=chooseComputerMove(game,strength===3?3:strength===2?2:1);if(ticket===generation&&m)await applyMove(m,true)},350)}
function chooseSquare(x,y){if(busy||game.status().over||($('#mode').value==='ai'&&game.turn==='b'))return;if(selected){const m=legal.find(m=>m.nx===x&&m.ny===y);if(m){void applyMove(m);return}}if(game.piece(x,y)?.c===game.turn){selected={x,y};legal=game.legalMoves(x,y);highlight();return}selected=null;legal=[];highlight()}
function connectPointers(){const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();let down=null;renderer.domElement.addEventListener('pointerdown',e=>{down={x:e.clientX,y:e.clientY}});renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down.x,e.clientY-down.y)>9){down=null;return}down=null;const rect=renderer.domElement.getBoundingClientRect();pointer.x=(e.clientX-rect.left)/rect.width*2-1;pointer.y=-(e.clientY-rect.top)/rect.height*2+1;raycaster.setFromCamera(pointer,camera);const hits=raycaster.intersectObjects([...pieceGroup.children,...boardGroup.children],true);if(!hits.length)return;const obj=hits[0].object,root=obj.userData.root||obj,d=root.userData;if(d.piece||d.square)chooseSquare(d.x,d.y)});const form=$('#moveForm');if(form)form.addEventListener('submit',e=>{e.preventDefault();const text=$('#moveInput').value.trim().toLowerCase(),match=/^([a-h])([1-8])([a-h])([1-8])([qrbn])?$/.exec(text);if(!match){notice('Enter e2e4 or e7e8q.');return}const x=match[1].charCodeAt(0)-97,y=8-Number(match[2]),nx=match[3].charCodeAt(0)-97,ny=8-Number(match[4]);if($('#mode').value==='ai'&&game.turn==='b'){notice('Computer is playing Black.');return}if(!game.legalMoves(x,y).some(m=>m.nx===nx&&m.ny===ny)){notice('That move is not legal.');return}void applyMove({x,y,nx,ny},false,match[5]||null).then(ok=>{if(ok)$('#moveInput').value=''})})}
function newGame(){generation++;clearTimeout(aiTimer);busy=false;game.reset();selected=null;legal=[];drawPieces();renderStatus()}
function connectButtons(){$('#newGame').onclick=newGame;$('#undo').onclick=()=>{if(busy)return;generation++;clearTimeout(aiTimer);if(!game.undo()){notice('No move to undo.');return}if($('#mode').value==='ai'&&game.turn==='b')game.undo();selected=null;legal=[];drawPieces();renderStatus()};$('#flip').onclick=()=>{camera.position.x*=-1;camera.position.z*=-1;orbit.update()};$('#sound').onclick=e=>{soundOn=!soundOn;e.currentTarget.textContent=soundOn?'Sound on':'Sound off';e.currentTarget.setAttribute('aria-pressed',String(soundOn))};$('#theme').onchange=e=>{if(busy)return;theme=e.target.value;createBoard();drawPieces()};$('#mode').onchange=newGame;$('#menuBtn').onclick=e=>{const c=$('#controls'),open=c.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',String(open))}}
function init(){try{scene=new THREE.Scene();scene.fog=new THREE.Fog(0x071019,15,35);camera=new THREE.PerspectiveCamera(43,1,.1,100);camera.position.set(8.5,10,9.5);renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;sceneEl.appendChild(renderer.domElement)}catch(error){stateEl.textContent='3D graphics unavailable';sceneEl.textContent='This browser could not start WebGL. '+error.message;return}orbit=new OrbitControls(camera,renderer.domElement);orbit.enableDamping=true;orbit.target.set(0,.25,0);orbit.minDistance=7;orbit.maxDistance=22;orbit.maxPolarAngle=1.47;orbit.update();scene.add(new THREE.HemisphereLight(0xd8f2ff,0x17202a,2.2));const light=new THREE.DirectionalLight(0xffffff,2.8);light.position.set(6,12,5);light.castShadow=true;light.shadow.mapSize.set(1024,1024);scene.add(light);boardGroup=new THREE.Group();pieceGroup=new THREE.Group();fxGroup=new THREE.Group();scene.add(boardGroup,pieceGroup,fxGroup);createBoard();drawPieces();renderStatus();connectPointers();connectButtons();const resize=()=>{const w=Math.max(1,sceneEl.clientWidth),h=Math.max(1,sceneEl.clientHeight);renderer.setSize(w,h,false);camera.aspect=w/h;camera.fov=camera.aspect<.85?62:43;camera.updateProjectionMatrix()};new ResizeObserver(resize).observe(sceneEl);resize();renderer.setAnimationLoop(()=>{orbit.update();renderer.render(scene,camera)})}
init();
