/* Subject plans own their learning state; global ambience never loads here. */
(() => {
  const id=document.currentScript.dataset.domain;let limit=18,selected=new Set(),domain;
  const level=document.querySelector('#subject-level'),type=document.querySelector('#subject-type'),list=document.querySelector('#subject-lessons'),status=document.querySelector('#subject-status');
  const render=()=>{const lessons=domain.lessons.filter(l=>(!level.value||l.level===level.value)&&(!type.value||l.type===type.value));list.replaceChildren(...lessons.slice(0,limit).map(l=>{const card=document.createElement('article');card.className='destination-card';const check=document.createElement('input');check.type='checkbox';check.checked=selected.has(l.id);check.addEventListener('change',()=>check.checked?selected.add(l.id):selected.delete(l.id));const label=document.createElement('label');label.append(check,' Add to my plan');const a=document.createElement('a');a.href='lesson.html?lesson='+encodeURIComponent(l.id);a.textContent=l.title;const p=document.createElement('p');p.textContent=[l.level,l.type,l.category].filter(Boolean).join(' · ');card.append(a,p,label);return card;}));status.textContent=`${lessons.length} matching records. ${selected.size} selected.`;document.querySelector('#subject-more').hidden=limit>=lessons.length;};
  fetch('assets/site-subjects.json').then(r=>{if(!r.ok)throw Error();return r.json();}).then(data=>{domain=data.domains.find(d=>d.id===id);if(!domain)throw Error();try{selected=new Set(JSON.parse(localStorage.getItem('jr-subject-plan-'+id)||'[]'));}catch{}for(const [el,key]of [[level,'level'],[type,'type']])for(const value of [...new Set(domain.lessons.map(l=>l[key]))].filter(Boolean).sort()){const o=document.createElement('option');o.value=value;o.textContent=value;el.append(o);}render();}).catch(()=>{status.textContent='Subject index unavailable. Use the browse links below.';});
  for(const el of [level,type])el.addEventListener('change',()=>{limit=18;render();});document.querySelector('#subject-more').onclick=()=>{limit+=18;render();};
  document.querySelector('#save-subject-plan').onclick=()=>{try{localStorage.setItem('jr-subject-plan-'+id,JSON.stringify([...selected]));status.textContent=`Saved ${selected.size} lessons in this browser.`;}catch{status.textContent='Storage unavailable. Your selections remain for this visit.';}};
  document.querySelector('#clear-subject-plan').onclick=()=>{selected.clear();try{localStorage.removeItem('jr-subject-plan-'+id);}catch{}render();};
})();
