const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const {chromium}=require('playwright');const root=path.resolve(process.env.PORTFOLIO_RUNTIME_ROOT||path.join(__dirname,'..'));
const server=http.createServer((req,res)=>{try{const name=decodeURIComponent(new URL(req.url,'http://local').pathname),file=path.resolve(root,'.'+name);if(!file.startsWith(root+path.sep))throw Error('outside');const ext=path.extname(file);res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.wasm':'application/wasm','.png':'image/png'})[ext]||'application/octet-stream');res.end(fs.readFileSync(file));}catch{res.writeHead(404);res.end();}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,executablePath:process.env.PORTFOLIO_BROWSER_EXECUTABLE||undefined,args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});const result={errors:[],missing:[],messages:[]};
let page;try{page=await browser.newPage({viewport:{width:1280,height:800}});result.console=[];page.on('console',m=>result.console.push(m.text()));page.on('pageerror',e=>result.errors.push(e.message));page.on('response',r=>{if(r.status()>=400)result.missing.push(r.url());});
await page.goto(`http://127.0.0.1:${server.address().port}/games/evil-wizard/play.html?mode=keyboard`,{waitUntil:'networkidle'});assert.equal(await page.locator('#champion option').count(),15);
await page.evaluate(()=>{window.__gameMessages=[];addEventListener('message',e=>{if(e.origin===location.origin)window.__gameMessages.push(e.data);});});await page.locator('#start').click();
await page.waitForFunction(()=>window.__gameMessages?.some(m=>m.type==='evil-wizard/ready'),null,{timeout:60000});
// The preserved export starts with a three-screen prologue requiring player input.
await page.frameLocator('#game').locator('canvas').click();
for(let i=0;i<3;i++){await page.keyboard.press('Space');await page.waitForTimeout(500);}
await page.waitForFunction(()=>window.__gameMessages?.some(m=>m.type==='evil-wizard/state'&&m.playing===true),null,{timeout:60000});result.messages=await page.evaluate(()=>window.__gameMessages.map(m=>m.type).filter(Boolean));
assert.deepEqual(result.errors,[]);assert.deepEqual(result.missing,[]);result.passed=true;console.log('PASS imported Evil Wizard: 15 champions, Godot/WASM/PCK startup and playing-state handshake.');
}catch(e){result.passed=false;result.failure=e.message;result.messages=await page.evaluate(()=>window.__gameMessages||[]);await page.screenshot({path:path.join(__dirname,"../docs/phase3-evidence/evil-wizard.png")});result.frames=await Promise.all(page.frames().map(async f=>({url:f.url(),text:await f.locator('body').innerText().catch(()=>'' )})));throw e;}finally{await browser.close();server.close();fs.mkdirSync(path.join(__dirname,'../docs/phase3-evidence'),{recursive:true});fs.writeFileSync(path.join(__dirname,'../docs/phase3-evidence/evil-wizard-browser.json'),JSON.stringify(result,null,2)+'\n');}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
