const assert=require('node:assert/strict');
const path=require('node:path');
module.exports=async({browser,base,output,failures})=>{
 const context=await browser.newContext({viewport:{width:844,height:390},isMobile:true,hasTouch:true});
 const page=await context.newPage();page.setDefaultTimeout(10000);
 page.on('pageerror',e=>failures.push('Live chess: '+e.message));
 const url=base+'/tests/run-live-site/games/3d-battle-chess/index.html';
 await page.goto(url,{waitUntil:'networkidle'});
 await page.locator('#jr-start-game').waitFor({state:'visible'});
 assert.equal(await page.locator('#jr-setup-view option[value="3d"]').isDisabled(),false,'Self-hosted Three starts the real live renderer');
 await page.locator('#jr-setup-mode').selectOption('local');
 await page.locator('#jr-start-game').click();
  await page.locator('#scene canvas').waitFor({state:'visible'});
 if(output)await page.screenshot({path:path.join(output,'chess-live-start-landscape.png')});
 if(!await page.locator('#boardMode').isVisible())await page.locator('#menuBtn').click();
 await page.locator('#boardMode').click();
 assert.equal(await page.locator('#boardMode').innerText(),'3D');
 await page.getByRole('button',{name:'e2: white pawn',exact:true}).click();
 await page.getByRole('button',{name:'e4: empty',exact:true}).click();
 await page.getByRole('button',{name:'e4: white pawn',exact:true}).waitFor({state:'visible'});
 assert.match(await page.locator('#turn').innerText(),/Black/);
 await page.locator('#boardMode').click();
 assert(await page.locator('#scene canvas').isVisible(),'Return to 3D');
 assert.equal(await page.locator('#boardMode').innerText(),'2D');
 if(output)await page.screenshot({path:path.join(output,'chess-live-3d-landscape.png')});
 await page.locator('#boardMode').click();
 assert(await page.getByRole('button',{name:'e4: white pawn',exact:true}).isVisible(),'Move survives 2D → 3D → 2D');
 if(!await page.locator('#undo').isVisible())await page.locator('#menuBtn').click();
 await page.locator('#undo').click();
 if(await page.locator('#controls').evaluate(el=>el.classList.contains('open')))await page.locator('#menuBtn').click();
 assert(await page.getByRole('button',{name:'e2: white pawn',exact:true}).isVisible(),'Undo operates on the shared engine');
 assert.equal(await page.locator('#log li').count(),0);
 if(output)await page.screenshot({path:path.join(output,'chess-live-2d-landscape.png')});
 await context.close();
 const fallback=await browser.newContext({viewport:{width:844,height:390}});
 await fallback.route('**/vendor/three.module.min.js',route=>route.abort());
 const safe=await fallback.newPage();await safe.goto(url,{waitUntil:'networkidle'});
 await safe.locator('#jr-start-game').waitFor({state:'visible'});
 assert(await safe.locator('#jr-setup-view option[value="3d"]').isDisabled(),await safe.locator('#jr-game-setup').innerText());
 await safe.locator('#jr-start-game').click();
 assert.match(await safe.locator('#boardMode').innerText(),/unavailable/);
 assert.equal(await safe.locator('#scene button').count(),64,'A working 2D board remains available when graphics cannot start');
 await fallback.close();console.log('PASS live chess: self-hosted 3D, phone controls, two-way views, shared moves, undo, graphics fallback');
};
