const assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const base=process.env.TEST_BASE_URL || 'http://localhost:8765';
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH || undefined,headless:true,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 const page=await browser.newPage({viewport:{width:430,height:820}});const errors=[];page.setDefaultTimeout(15000);
 page.on('pageerror',e=>errors.push(e.message));
 if(process.env.THREE_MODULE_ROOT)await page.route('https://cdn.jsdelivr.net/npm/three@0.180.0/**',r=>r.fulfill({path:process.env.THREE_MODULE_ROOT+'/'+r.request().url().split('@0.180.0/')[1],contentType:'text/javascript'}));
 await page.goto(base+'/games/3d-battle-chess/');
 const toggle=page.locator('#boardMode');
 await page.waitForFunction(()=>document.querySelector('#boardMode').dataset.view==='3d'&&!document.querySelector('#boardMode').disabled);
 await page.locator('#menuBtn').click();
 await page.selectOption('#mode','local');
 await page.fill('#moveInput','e2e4');await page.locator('#moveForm button').click();
 assert.equal(await page.locator('#log li').count(),1);
 await toggle.click();await page.waitForFunction(()=>document.querySelector('#boardMode').dataset.view==='2d');
 assert.equal(await toggle.textContent(),'Use 3D board');
 assert.equal(await page.locator('#log li').count(),1);
 assert.equal(await page.locator('.square-2d').count(),64);
 await page.fill('#moveInput','e7e5');await page.locator('#moveForm button').click();
 assert.equal(await page.locator('#log li').count(),2);
 await toggle.click();await page.waitForFunction(()=>document.querySelector('#boardMode').dataset.view==='3d'&&!document.querySelector('#boardMode').disabled);
 assert.equal(await page.locator('#log li').count(),2);
 assert.equal(await page.locator('#scene canvas').count(),1);
 for(let i=0;i<3;i++){await toggle.click();await toggle.click();await page.waitForFunction(()=>!document.querySelector('#boardMode').disabled);}
 await page.fill('#moveInput','g1f3');await page.locator('#moveForm button').click();
 assert.equal(await page.locator('#log li').count(),3);
 await page.locator('#undo').click();assert.equal(await page.locator('#log li').count(),2);
 await toggle.click();await page.locator('#undo').click();assert.equal(await page.locator('#log li').count(),1);
 await page.locator('#newGame').click();assert.equal(await page.locator('#log li').count(),0);
 assert.deepEqual(errors,[]);
 console.log('PASS: 3D→2D→3D, repeated switching, shared moves, keyboard entry, undo and new game');
 const failed=await browser.newPage({viewport:{width:430,height:820}});failed.setDefaultTimeout(12000);
 await failed.route('https://cdn.jsdelivr.net/**',r=>r.abort());
 await failed.goto(base+'/games/3d-battle-chess/');
 await failed.waitForFunction(()=>document.querySelector('#boardMode').dataset.view==='2d'&&!document.querySelector('#boardMode').disabled);
 await failed.locator('#menuBtn').click();await failed.selectOption('#mode','local');
 await failed.fill('#moveInput','e2e4');await failed.locator('#moveForm button').click();
 await failed.locator('#boardMode').click();await failed.waitForFunction(()=>!document.querySelector('#boardMode').disabled);
 assert.equal(await failed.locator('#log li').count(),1);assert.equal(await failed.locator('.square-2d').count(),64);
 assert.match(await failed.locator('#state').textContent(),/3D unavailable/);
 console.log('PASS: unavailable 3D and retry preserve a playable 2D game');
 const font=await browser.newPage({viewport:{width:430,height:820}});
 await font.goto(base+'/learn.html');await font.evaluate(()=>document.fonts.ready);
 const actual=await font.locator('.brand span').evaluate(e=>{const s=getComputedStyle(e);return [s.fontFamily,s.fontSize,s.fontWeight]});
 await font.goto(base+'/');await font.evaluate(()=>document.fonts.ready);
 const expected=await font.locator('.brand span').evaluate(e=>{const s=getComputedStyle(e);return [s.fontFamily,s.fontSize,s.fontWeight]});
 assert.deepEqual(actual,expected);console.log('PASS: mobile learning name matches homepage font, size, weight:',actual);
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
