const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),crypto=require('node:crypto');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'../staging/website-2.0-runtime');
const manifest=JSON.parse(fs.readFileSync(path.resolve(root,'../website-2.0-runtime-manifest.json')));
const files=new Map(manifest.files.map(f=>[f.path,f]));
const types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.mp4':'video/mp4'};
const server=http.createServer((req,res)=>{const rel=decodeURIComponent(new URL(req.url,'http://local').pathname).slice(1);if(!files.has(rel)){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',types[path.extname(rel)]||'application/octet-stream');fs.createReadStream(path.join(root,rel)).pipe(res);});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;const browser=await chromium.launch({headless:true,executablePath:process.env.PORTFOLIO_BROWSER_EXECUTABLE});
try{const page=await browser.newPage();await page.route('https://**/*',r=>r.abort());await page.goto(base+'/project-fusion.html',{waitUntil:'domcontentloaded'});await page.locator('video[controls]').evaluate(v=>{v.preload='metadata';v.load();});await page.waitForFunction(()=>{const v=document.querySelector('video[controls]');return v.readyState>=1&&Number.isFinite(v.duration)&&v.duration>0;},null,{timeout:60000});const video=await page.locator('video[controls]').evaluate(v=>({duration:v.duration,width:v.videoWidth,height:v.videoHeight,source:v.currentSrc}));assert(video.width>0&&video.height>0);assert(video.source.startsWith(base+'/assets/'));
const downloads=[...files.keys()].filter(p=>/\.(pdf|docx|zip)$/.test(p));assert(downloads.some(p=>p.endsWith('Recovery_Readiness_Auditor.zip')));for(const p of downloads){const r=await page.request.get(base+'/'+p);assert.equal(r.status(),200,p);assert.equal(crypto.createHash('sha256').update(await r.body()).digest('hex'),files.get(p).sha256,p);}
assert.equal((await page.request.get(base+'/geometric-lab/METHODS.md')).status(),200);await page.goto(base+'/qubit-preview-20260921/index.html',{waitUntil:'domcontentloaded'});await page.locator('[data-angle="0"]').click();await page.locator('#measure').click();assert.equal(await page.locator('#count1').innerText(),'0');assert(Number((await page.locator('#count0').innerText()).replaceAll(',',''))>0);
await page.goto(base+'/geometric-lab/index.html',{waitUntil:'domcontentloaded'});await page.locator('#shape').selectOption('sphere');assert.match(await page.locator('#view-title').innerText(),/Sphere/);await page.locator('#density').selectOption('600');await page.locator('#estimate').click();await page.waitForFunction(()=>document.querySelector('#method-badge').textContent==='Local quadratic fit',null,{timeout:30000});await page.locator('[data-tab="models"]').click();assert(await page.locator('#case option').count()>0);await page.locator('#model-display').selectOption('error');assert((await page.locator('#metrics').innerText()).length>0);await page.locator('[data-tab="diffusion"]').click();await page.locator('#time').fill('5');assert.equal(await page.locator('#time').inputValue(),'5');await page.locator('[data-tab="inverse"]').click();await page.locator('#resample').click();assert(await page.locator('#posterior-chart').isVisible());
const evidence={labChecks:['Qubit deterministic zero-state sampling','Geometric local curvature worker','recorded neural outputs','diffusion time control','inverse posterior'],sourceCommit:manifest.sourceCommit,video:{...video,source:'assets/fusion-presentation.mp4'},downloads,externalNetworkBlocked:true};fs.writeFileSync(path.resolve(__dirname,'../docs/phase3-evidence/media-downloads.json'),JSON.stringify(evidence,null,2)+'\n');console.log('PASS staged Fusion metadata, video dimensions, hashed resume/recovery downloads and Qubit/Geometric interactive checks.');
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});

