/* Behavioral ownership and failure checks against the staged package only. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');const {chromium}=require('playwright');
const root=path.resolve(__dirname,'../staging/website-2.0-runtime'),report=JSON.parse(fs.readFileSync(path.resolve(__dirname,'../staging/website-2.0-runtime-manifest.json'))),files=new Set(report.files.map(f=>f.path));
const server=http.createServer((req,res)=>{let p=decodeURIComponent(new URL(req.url,'http://local').pathname).slice(1);if(!p||p.endsWith('/'))p+='index.html';if(!files.has(p)){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',({'.js':'text/javascript','.json':'application/json','.html':'text/html','.css':'text/css','.svg':'image/svg+xml','.wav':'audio/wav','.mp3':'audio/mpeg'})[path.extname(p)]||'application/octet-stream');res.end(fs.readFileSync(path.join(root,p)));});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`,browser=await chromium.launch({headless:true,executablePath:process.env.PORTFOLIO_BROWSER_EXECUTABLE});const results=[];try{
 const c=await browser.newContext({viewport:{width:390,height:844}});await c.route('https://**/*',r=>r.abort());await c.addInitScript(()=>{HTMLMediaElement.prototype.play=function(){if(this.tagName==='AUDIO')return Promise.reject(new DOMException('Denied by test policy','NotAllowedError'));return Promise.resolve();};});const p=await c.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.goto(base+'/index.html',{waitUntil:'domcontentloaded'});assert.equal(await p.locator('header [data-scene-audio]').count(),1);assert.equal(await p.evaluate(()=>SiteAudio.volume),.05);await p.waitForFunction(()=>SiteAudio.autoplayBlocked);await p.locator('[data-scene-audio]').click();assert.equal(await p.locator('#ambient-volume').getAttribute('step'),'5');await p.locator('#ambient-volume').fill('10');assert.equal(await p.evaluate(()=>SiteAudio.volume),.1);await p.locator('.scene-sound-mute').click();assert(await p.evaluate(()=>SiteAudio.muted));await p.reload({waitUntil:'domcontentloaded'});assert(await p.evaluate(()=>SiteAudio.muted));assert.equal(await p.evaluate(()=>SiteAudio.volume),.1);results.push('quiet default, 5% steps, mute/volume persistence, denied autoplay state');
 await p.locator('#search-open').click();await p.locator('#search-input').fill('quantum');await p.locator('#search-results a').first().waitFor();assert(await p.locator('#search-results a[href^="lesson.html?lesson="]').count()>0);await p.keyboard.press('Escape');await p.waitForFunction(()=>document.activeElement===document.querySelector('#search-open'));results.push('global search includes dedicated lessons and returns focus');
 await p.locator('#menu').click();await p.mouse.click(5,830);assert.equal(await p.locator('#menu').getAttribute('aria-expanded'),'false');await p.locator('#menu').click();await p.keyboard.press('Escape');assert(await p.locator('#menu').evaluate(e=>e===document.activeElement));assert.equal(await p.locator('[data-solar="portfolio"] a').count(),9);
 await p.goto(base+'/learn.html',{waitUntil:'domcontentloaded'});assert.equal(await p.locator('[data-solar="learning"] a').count(),7);assert(await p.locator('[data-solar="learning"]').isVisible());assert.equal(await p.locator('header [data-scene-audio]').count(),1);await p.evaluate(()=>document.dispatchEvent(new CustomEvent('portfolio:ambient-suppression',{detail:{active:true}})));assert(await p.evaluate(()=>SiteAudio.suppressed));results.push('distinct solar data; learning suppression');
 for(const route of ['projects.html','project-fusion.html','learn-cloud.html','learn-browse.html','lesson.html?lesson=cloud-url-journey']){await p.goto(base+'/'+route,{waitUntil:'domcontentloaded'});assert(await p.evaluate(()=>!window.SiteAudio||SiteAudio.suppressed),route);assert.equal(await p.locator('header [data-scene-audio]').count(),0,route);}results.push('ambience suppressed on projects, subject plans and lessons');
 await p.goto(base+'/learn-cloud.html',{waitUntil:'domcontentloaded'});await p.locator('#subject-level').selectOption('Advanced');assert((await p.locator('#subject-lessons article p').first().textContent()).includes('Advanced'));await p.locator('#subject-level').selectOption('');await p.locator('#subject-lessons input').first().check();await p.locator('#save-subject-plan').click();await p.reload({waitUntil:'domcontentloaded'});assert(await p.locator('#subject-lessons input').first().isChecked());await p.locator('#subject-lessons a').first().click();await p.waitForURL('**/lesson.html?lesson=*');results.push('subject plan persists and opens dedicated lesson');
 await p.emulateMedia({reducedMotion:'reduce'});await p.goto(base+'/index.html',{waitUntil:'domcontentloaded'});assert(await p.evaluate(()=>PortfolioTheme.isPaused()));const before=await p.locator('.scene-canvas').evaluate(e=>e.toDataURL());await p.waitForTimeout(200);assert.equal(await p.locator('.scene-canvas').evaluate(e=>e.toDataURL()),before);results.push('reduced-motion scene is stationary');
 await c.close();const blocked=await browser.newContext();await blocked.route('https://**/*',r=>r.abort());await blocked.addInitScript(()=>{Object.defineProperty(window,'localStorage',{get(){throw new DOMException('Blocked','SecurityError')}});HTMLCanvasElement.prototype.getContext=()=>null;HTMLMediaElement.prototype.play=()=>Promise.reject(new DOMException('Denied','NotAllowedError'));});const b=await blocked.newPage();await b.goto(base+'/index.html',{waitUntil:'domcontentloaded'});await b.locator('[data-scene-audio]').click();await b.locator('#ambient-volume').fill('10');assert.equal(await b.evaluate(()=>SiteAudio.volume),.1);assert(await b.locator('.scene-sound-panel').isVisible());await b.locator('[data-theme-toggle]').click();assert.equal(await b.locator('html').getAttribute('data-theme'),'light');results.push('canvas unavailable and blocked storage retain sound/theme controls');await blocked.close();assert.deepEqual(errors,[]);console.log('PASS ownership/failure contracts: '+results.length);
}finally{await browser.close();server.close();fs.writeFileSync(path.resolve(__dirname,'../docs/phase3-evidence/ownership-browser.json'),JSON.stringify({sourceCommit:report.sourceCommit,passed:results,physicalDevices:false},null,2)+'\n');}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
