/* Focused behavioral regressions for the protected-refinement pass. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),vm=require('node:vm');
const playwright=require(process.env.PORTFOLIO_PLAYWRIGHT||'playwright');
const engine=process.env.PORTFOLIO_ENGINE||'chromium';
const root=path.resolve(process.env.PORTFOLIO_RUNTIME_ROOT||path.join(__dirname,'../staging/website-2.0-runtime'));
const output=path.resolve(process.env.PORTFOLIO_QA_DIR||path.join(__dirname,'../visual-qa/refinement'));fs.mkdirSync(output,{recursive:true});
const sandbox={window:{}};vm.runInNewContext(fs.readFileSync(path.join(root,'knowledge-data.js'),'utf8'),sandbox);const D=sandbox.window.JR_KNOWLEDGE;
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.png':'image/png','.webp':'image/webp','.jpg':'image/jpeg','.mp3':'audio/mpeg','.wav':'audio/wav','.wasm':'application/wasm'};
const server=http.createServer((req,res)=>{let f=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname));if(!f.startsWith(root+'/')&&f!==root){res.writeHead(403).end();return}try{if(fs.statSync(f).isDirectory())f=path.join(f,'index.html');res.setHeader('Content-Type',mime[path.extname(f)]||'application/octet-stream');fs.createReadStream(f).pipe(res)}catch{res.writeHead(404).end()}});
const report={engine,ai:[],learning:[],errors:[],physicalDevices:false};
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}/`;
const browser=await playwright[engine].launch({headless:true,executablePath:process.env.PORTFOLIO_BROWSER_EXECUTABLE||undefined,args:engine==='chromium'?['--no-sandbox','--disable-dev-shm-usage']:[]});
try{
 const c=await browser.newContext({viewport:{width:390,height:844}});await c.route('https://**/*',r=>r.abort());const p=await c.newPage();p.on('pageerror',e=>report.errors.push(e.message));
 for(const file of fs.readdirSync(root).filter(f=>/^ai-.*\.html$/.test(f)&&fs.readFileSync(path.join(root,f),'utf8').includes('data-ai-build='))){
  await p.goto(base+file,{waitUntil:'domcontentloaded'});await p.locator('[data-ai-reset]').waitFor();await p.locator('#ai-lab-root').scrollIntoViewIfNeeded();await p.waitForFunction(()=>document.querySelector('[data-output]').innerText.trim().length>0);const initial=await p.locator('[data-output]').innerText();assert(initial.trim(),file+' result');
  await p.locator('[data-ai-compare]').click();assert.equal(await p.locator('[data-ai-comparison]').isVisible(),true);
  const input=p.locator('#ai-lab-root input').first();if(await input.count()){const type=await input.getAttribute('type');if(type==='checkbox')await input.setChecked(!await input.isChecked());else if(type==='range')await input.fill(await input.getAttribute('max'));else await input.fill('2');}
  const bad=p.locator('#ai-lab-root input[type=number]').first();if(await bad.count()){await bad.fill('');assert(await p.locator('[data-input-error]').isVisible(),file+': blank numeric input is not fabricated as zero');assert.equal(await p.locator('[data-ai-compare]').isEnabled(),false);}
  await p.locator('[data-ai-reset]').click();assert.equal(await p.locator('[data-output]').innerText(),initial,file+': reset restores known state');assert.equal(await p.locator('[data-ai-comparison]').isVisible(),false);
  for(const width of [320,430,820,1024,1440,1920]){await p.setViewportSize({width,height:900});for(const theme of ['dark','light']){await p.evaluate(t=>PortfolioTheme.setTheme(t),theme);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),file+' '+width+' '+theme);}}
  report.ai.push(file);
 }
 const visitAI=async file=>{await p.goto(base+file);await p.locator('#ai-lab-root').scrollIntoViewIfNeeded();await p.waitForFunction(()=>document.querySelector('[data-output]').innerText.trim().length>0);};
 await visitAI('ai-llm.html');for(const sel of ['#l1','#l2','#l3'])await p.locator(sel).fill('2');const probabilities=await p.locator('[data-output] output').allTextContents();assert(probabilities.every(x=>x==='33.3333%'));
 await visitAI('ai-memory.html');await p.locator('#qx').fill('0');await p.locator('#qy').fill('0');assert.match(await p.locator('[data-output]').innerText(),/undefined/);
 await visitAI('ai-graph-neural-networks.html');await p.locator('#neighbors').fill('1,,3');assert(await p.locator('[data-input-error]').isVisible());await p.locator('#neighbors').fill('1,2,3');assert.match(await p.locator('[data-output]').innerText(),/aggregate = 2/);
 await visitAI('ai-multi-agent.html');await p.locator('#capacity').fill('-1');assert(await p.locator('[data-input-error]').isVisible());
 await visitAI('ai-computer-vision.html');await p.locator('#kernel').selectOption('edge');assert.match(await p.locator('[data-output]').innerText(),/240/);await p.locator('#kernel').selectOption('sharpen');assert.match(await p.locator('[data-output]').innerText(),/170/);
 const models=[...new Map(D.lessons.filter(l=>l.interactive).map(l=>[l.interactive,l])).values()];
 for(const lesson of models){await p.goto(base+`lesson.html?lesson=${encodeURIComponent(lesson.id)}&view=visual`,{waitUntil:'domcontentloaded'});await p.locator('[data-teaching-model]').waitFor();assert.equal(await p.locator('[data-teaching-model]').getAttribute('data-teaching-model'),lesson.interactive);assert(await p.locator('[data-stage] button,[data-stage] input,[data-stage] select,[data-stage] textarea,[data-controls] input,[data-controls] select,[data-controls] button').count()>0,lesson.interactive+': executable controls, not fallback text');assert.doesNotMatch(await p.locator('[data-stage]').textContent(),/no interactive model attached/);await p.locator('[data-reset-model]').click();assert(await p.locator('[data-stage]').innerHTML(),lesson.interactive+': reset retains model');report.learning.push(lesson.interactive);console.log('MODEL',lesson.interactive);}
 const visitModel=async type=>{const l=D.lessons.find(l=>l.interactive===type);await p.goto(base+'lesson.html?lesson='+l.id+'&view=lab');await p.locator('[data-controls]').scrollIntoViewIfNeeded();};
 await visitModel('integral');await p.locator('[data-int-range]').fill('2');assert.equal(await p.locator('[data-int-a]').textContent(),'3.3750');await p.locator('[data-int-range]').fill('60');assert(Math.abs(Number(await p.locator('[data-int-a]').textContent())-8.77625)<.000051,'60-rectangle sum rounded to four decimals');
 await visitModel('seriescircuit');assert.equal(await p.locator('[data-si]').textContent(),'0.400 A');assert.equal(await p.locator('[data-sv1]').textContent(),'4.00 V');assert.equal(await p.locator('[data-sv23]').textContent(),'8.00 V');
 await visitModel('switchlab');assert.deepEqual(await p.locator('[data-switch-dst] option').allTextContents(),['Host A','Host B','Host C']);await p.locator('[data-switch-send]').click();assert.match(await p.locator('[data-switch-out]').textContent(),/floods/);await p.locator('[data-switch-src]').selectOption('1');await p.locator('[data-switch-dst]').selectOption('0');await p.locator('[data-switch-send]').click();assert.match(await p.locator('[data-switch-out]').textContent(),/forwarded to Port 1/);
 await visitModel('kubescheduler');await p.locator('[data-kcpu]').fill('10');await p.locator('[data-kschedule]').click();assert.match(await p.locator('[data-ksched-out]').textContent(),/No feasible node/);
 await visitModel('quorum');await p.locator('[data-qfails]').fill('3');assert.equal(await p.locator('[data-qok]').textContent(),'No');
 await visitModel('sqljoin');assert.equal(await p.locator('[data-join-result]>span').count(),2);await p.locator('[data-join-type]').selectOption('left');assert.equal(await p.locator('[data-join-result]>span').count(),3);await p.locator('[data-join-type]').selectOption('full');assert.equal(await p.locator('[data-join-result]>span').count(),4);
 await visitModel('riskmatrix');await p.locator('[data-rl]').fill('5');await p.locator('[data-ri]').fill('5');assert.equal(await p.locator('[data-risk-s]').textContent(),'25');assert.equal(await p.locator('[data-risk-b]').textContent(),'High');
 await visitModel('btree');await p.locator('[data-btree-key]').selectOption('22');await p.locator('[data-btree-find]').click();assert.match(await p.locator('[data-btree-out]').textContent(),/not found/);
 await visitModel('subnet');assert.equal(await p.locator('[data-net]').textContent(),'192.168.10.0/26');await p.locator('[data-ip]').fill('10..0.1');await p.locator('[data-controls] button').click();assert(await p.locator('[data-subnet-error]').isVisible());assert.equal(await p.locator('[data-net]').textContent(),'—');await p.locator('[data-ip]').fill('192.0.2.1');await p.locator('[data-prefix]').fill('1.5');await p.locator('[data-controls] button').click();assert(await p.locator('[data-subnet-error]').isVisible());await p.locator('[data-prefix]').fill('31');await p.locator('[data-controls] button').click();assert.equal(await p.locator('[data-hosts]').textContent(),'2');
 await visitModel('roofline');await p.evaluate(()=>{window.__roofPoints=[];const ctx=document.querySelector('[data-stage] canvas').getContext('2d'),line=ctx.lineTo.bind(ctx);ctx.lineTo=(x,y)=>{window.__roofPoints.push([x,y]);line(x,y)};});await p.locator('[data-rf-b]').fill('10');await p.locator('[data-rf-a]').fill('50');assert.equal(await p.locator('[data-rf-out]').textContent(),'500 GFLOP/s');assert.deepEqual(await p.evaluate(()=>window.__roofPoints.at(-1)),[680,127.5],'unreachable compute ceiling must not appear on the roofline');
 await visitModel('kuberollout');await p.locator('[data-r-s]').fill('0');await p.locator('[data-r-u]').fill('0');assert.equal(await p.locator('[data-r-next]').isEnabled(),false);await p.locator('[data-r-u]').fill('1');for(let step=0;step<12&&await p.locator('[data-r-next]').isEnabled();step++){await p.locator('[data-r-next]').click();const total=Number(await p.locator('[data-r-old]').textContent())+Number(await p.locator('[data-r-new]').textContent());assert(total>=3&&total<=4,'zero-surge rollout bounds');}assert.equal(await p.locator('[data-r-old]').textContent(),'0');assert.equal(await p.locator('[data-r-new]').textContent(),'4');
 await visitModel('wave');await p.evaluate(()=>{window.__activeOscillators=0;const start=OscillatorNode.prototype.start,stop=OscillatorNode.prototype.stop;OscillatorNode.prototype.start=function(...args){window.__activeOscillators++;return start.apply(this,args)};OscillatorNode.prototype.stop=function(...args){window.__activeOscillators--;return stop.apply(this,args)};});await p.locator('[data-hear]').click();assert.equal(await p.evaluate(()=>window.__activeOscillators),1);await p.locator('[data-lesson-view=practice]').click();assert.equal(await p.evaluate(()=>window.__activeOscillators),0);assert.equal(await p.evaluate(()=>SiteAudio.suppressed),false);
 await p.goto(base+'lesson.html?lesson=not-a-current-record');assert.match(await p.locator('.lesson-title').textContent(),/not found/);assert(await p.locator('#lesson-article a[href="learn-browse.html"]').isVisible());
 const subjectContext=await browser.newContext();await subjectContext.route('https://**/*',r=>r.abort());let subjectFails=true;await subjectContext.route('**/assets/site-subjects.json',r=>subjectFails?r.abort():r.continue());const subject=await subjectContext.newPage();subject.on('pageerror',e=>report.errors.push(e.message));await subject.goto(base+'learn-cloud.html');await subject.locator('.subject-retry').waitFor({state:'visible'});assert.equal(await subject.locator('#save-subject-plan').isEnabled(),false);subjectFails=false;await subject.locator('.subject-retry').click();await subject.locator('#subject-lessons input').first().check();await subject.locator('#save-subject-plan').click();await subject.reload();assert(await subject.locator('#subject-lessons input').first().isChecked());await subjectContext.close();
 await p.setViewportSize({width:390,height:844});await p.goto(base+'lesson.html?lesson=cloud-url-journey&view=lab');await p.locator('[data-lab-notes]').fill('Prediction: DNS succeeds while TCP 443 is blocked.');await p.reload();assert.equal(await p.locator('[data-lab-notes]').inputValue(),'Prediction: DNS succeeds while TCP 443 is blocked.');await p.locator('[data-controls] button').click();await p.locator('[data-lesson-view=practice]').click();await p.waitForTimeout(5200);assert.equal(await p.locator('[data-stage]').count(),0,'closed lab timer cannot recreate its stage');
 const l=D.lessons.find(l=>l.id==='cloud-url-journey');await p.locator(`[data-option="${l.quiz.answer}"]`).click();assert.match(await p.locator('#quiz-feedback').innerText(),/Correct/);await p.locator('[data-quiz-retry]').click();assert.equal(await p.locator('.quiz-options button:enabled').count(),l.quiz.options.length);await p.locator(`[data-option="${(l.quiz.answer+1)%l.quiz.options.length}"]`).click();assert.match(await p.locator('#quiz-feedback').innerText(),/Not quite/);
 await p.goto(base+'learn-mastery.html');assert(await p.locator('[data-review-queue] a[href*="cloud-url-journey"]').isVisible(),'quiz schedules a visible review');
 await p.goto(base+'lesson.html?lesson=cloud-url-journey&view=review');await p.locator('[data-review-days="3"]').click();const plan=await p.evaluate(()=>JSON.parse(localStorage.getItem('jr-knowledge-review-plan-v1')));assert.equal(plan['cloud-url-journey'].source,'manual');
 // Scope narration to its lifetime and preserve mute after it releases ambience.
 await p.evaluate(()=>{localStorage.setItem('jr-site-ambient-muted-v3','1');window.__utterances=[];speechSynthesis.speak=u=>window.__utterances.push(u);speechSynthesis.cancel=()=>{};});await p.locator('#listen-full').click();assert(await p.evaluate(()=>SiteAudio.suppressed));await p.locator('#stop-audio').click();assert.equal(await p.evaluate(()=>SiteAudio.suppressed),false);assert.equal(await p.locator('#stop-audio').isVisible(),false);
 // A failed teaching chunk can be retried without destroying local working notes.
 const retryContext=await browser.newContext();await retryContext.route('https://**/*',r=>r.abort());let fail=true;await retryContext.route('**/deep-learning/cloud/networking.json',r=>fail?r.abort():r.continue());const retry=await retryContext.newPage();retry.on('pageerror',e=>report.errors.push(e.message));await retry.goto(base+'lesson.html?lesson=cloud-url-journey&view=lab');await retry.locator('[data-retry-pack]').waitFor();await retry.locator('[data-lab-notes]').fill('Keep this prediction during recovery.');fail=false;await retry.locator('[data-retry-pack]').click();await retry.locator('[data-retry-pack]').waitFor({state:'detached'});assert.equal(await retry.locator('[data-lab-notes]').inputValue(),'Keep this prediction during recovery.');await retryContext.close();
 for(const [name,url,selector] of [['teaching', 'lesson.html?lesson=cloud-url-journey&view=visual','#visual-map'],['ai-matrix','ai-computer-vision.html','#ai-lab-root'],['review','learn-mastery.html','[data-review-queue]']]){await p.goto(base+url);for(const width of [390,1440]){await p.setViewportSize({width,height:900});for(const theme of ['dark','light']){await p.evaluate(t=>PortfolioTheme.setTheme(t),theme);await p.locator(selector).evaluate(e=>scrollTo(0,e.getBoundingClientRect().top+scrollY-130));await p.waitForTimeout(150);await p.screenshot({path:path.join(output,`${name}-${width}-${theme}.png`),animations:'disabled'});}}}
 report.performance=[];for(const route of ['learn.html','lesson.html?lesson=cloud-url-journey&view=visual']){await p.goto(base+route);report.performance.push({route,...await p.evaluate(()=>({nodes:document.querySelectorAll('*').length,domContentLoaded:performance.getEntriesByType('navigation')[0].domContentLoadedEventEnd}))});}
 assert.deepEqual(report.errors,[]);assert.equal(report.ai.length,19);assert.equal(report.learning.length,66);report.passed=true;console.log('PASS refinement: 19 AI experiments, numerical/invalid-input cases, 66 visual/model pairs, local lab notes, timer cleanup, quiz retry, review queue, narration lifetime, teaching-pack retry and six responsive widths in both themes.');
 await c.close();
}finally{fs.writeFileSync(path.join(output,`refinement-${engine}.json`),JSON.stringify(report,null,2));await browser.close();server.close();}
})().catch(e=>{console.error(e);server.close();process.exitCode=1});
