/* Authoritative responsive contract: isolated bytes, all routes, no overflow masking. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'../staging/website-2.0-runtime'),manifest=JSON.parse(fs.readFileSync(path.resolve(root,'../website-2.0-runtime-manifest.json'))),files=new Set(manifest.files.map(f=>f.path));
const matrix=[[320,568],[360,800],[375,812],[390,844],[393,852],[412,915],[430,932],[768,1024],[820,1180],[1024,768],[1152,864],[1280,720],[1366,768],[1440,900],[1536,864],[1920,1080],[2560,1440],[3440,1440],[3840,2160],[844,390],[568,320]];
const mime={'.js':'text/javascript','.css':'text/css','.html':'text/html','.json':'application/json','.svg':'image/svg+xml','.wasm':'application/wasm','.mp4':'video/mp4','.wav':'audio/wav','.mp3':'audio/mpeg'};
const server=http.createServer((req,res)=>{let p=decodeURIComponent(new URL(req.url,'http://local').pathname).slice(1);if(!p||p.endsWith('/'))p+='index.html';if(!files.has(p)){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',mime[path.extname(p)]||'application/octet-stream');fs.createReadStream(path.join(root,p)).pipe(res);});

(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;const browser=await chromium.launch({headless:true,executablePath:process.env.PORTFOLIO_BROWSER_EXECUTABLE});const checked=[];try{const p=await browser.newPage();await p.route('https://**/*',r=>r.abort());const contained=async locator=>{const box=await locator.boundingBox();assert(box,'visible control');const size=p.viewportSize();assert(box.x>=-1&&box.x+box.width<=size.width+1,'horizontal containment');assert(box.y>=-1&&box.y+box.height<=size.height+1,'vertical containment '+p.url()+' '+JSON.stringify(box)+' viewport '+JSON.stringify(size));};
for(const route of [...files].filter(f=>f.endsWith('.html')&&!f.includes('/'))){await p.goto(base+'/'+route,{waitUntil:'domcontentloaded'});if(!await p.locator('.site-global-header').count())continue;for(const [width,height]of [[320,568],[768,1024],[1440,900]]){await p.setViewportSize({width,height});await p.evaluate(()=>scrollTo(0,0));const menu=p.locator('#menu,#mobile-menu');await menu.click();assert.equal(await menu.getAttribute('aria-expanded'),'true');await contained(p.locator('#primary-nav'));await p.keyboard.press('Escape');assert(await menu.evaluate(e=>e===document.activeElement));await p.locator('[data-scene-audio]').click();await contained(p.locator('.scene-sound-panel'));await p.keyboard.press('Escape');assert(await p.locator('[data-scene-audio]').evaluate(e=>e===document.activeElement));await p.locator('#search-open').click();if(await p.locator('#search-dialog').count()){await contained(p.locator('#search-dialog'));await p.keyboard.press('Escape');}else {await p.waitForFunction(()=>['knowledge-search','glossary-search','vnext-path-search'].includes(document.activeElement?.id),null,{timeout:2500});}}checked.push(route);console.log('HEADER',route);}
for(const [width,height]of [[320,568],[768,1024],[1440,900],[3840,2160]]){await p.setViewportSize({width,height});await p.goto(base+'/index.html',{waitUntil:'domcontentloaded'});for(const theme of ['dark','light']){await p.evaluate(t=>PortfolioTheme.setTheme(t,false),theme);const profile=p.locator('.about-imagery');const text=await profile.innerText();assert(text.includes('Dual major: Electrical & Computer Engineering + Computer Science'));assert(text.includes('Data Science minor')&&text.includes('Mathematics minor')&&text.includes('Physics minor')&&text.includes('Honors College'));assert(text.includes('MIT Center for Quantum Engineering')&&text.includes('MIT xPRO')&&text.includes('Tuition-based professional study'));assert(!text.includes('planned interdisciplinary')&&!text.includes('not an official completed second major'));await profile.screenshot({path:path.resolve(__dirname,`../docs/responsive-evidence/hero-${width}-${theme}.png`),animations:'disabled'});}await p.goto(base+'/learn.html',{waitUntil:'domcontentloaded'});assert.equal(await p.locator('.depth-ladder button').count(),8);await p.locator('.depth-ladder button').last().click();assert(await p.locator('.depth-ladder button').last().evaluate(e=>e.classList.contains('active')));await p.locator('.depth-planner').screenshot({path:path.resolve(__dirname,`../docs/responsive-evidence/route-${width}.png`),animations:'disabled'});}
// Extrema proof for every orbit phase, including parallax and an intentionally conservative 90px paint radius.
for(const rx of [.14,.19,.24,.285,.33])for(let angle=0;angle<Math.PI*2;angle+=.005){const x=400+Math.cos(angle)*800*rx;assert(x-10-90>=0&&x+10+90<=800);}for(const ry of [.09,.13,.17,.21,.25])for(let angle=0;angle<Math.PI*2;angle+=.005){const y=252+Math.sin(angle)*560*ry;assert(y-6-90>=0&&y+6+90<=560);}
fs.writeFileSync(path.resolve(__dirname,'../docs/responsive-evidence/components.json'),JSON.stringify({sourceCommit:manifest.sourceCommit,headerRoutes:checked,viewports:[[320,568],[768,1024],[1440,900]],solarExtrema:'all phases, parallax and conservative 90px paint radius',education:true},null,2)+'\n');console.log('PASS global header menus, sound panels, search, education, ladder and mathematical solar extrema.');
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
