/* Authoritative responsive contract: isolated bytes, all routes, no overflow masking. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'../staging/website-2.0-runtime'),manifest=JSON.parse(fs.readFileSync(path.resolve(root,'../website-2.0-runtime-manifest.json'))),files=new Set(manifest.files.map(f=>f.path));
const matrix=[[320,568],[360,800],[375,812],[390,844],[393,852],[412,915],[430,932],[768,1024],[820,1180],[1024,768],[1152,864],[1280,720],[1366,768],[1440,900],[1536,864],[1920,1080],[2560,1440],[3440,1440],[3840,2160],[844,390],[568,320]];
const mime={'.js':'text/javascript','.css':'text/css','.html':'text/html','.json':'application/json','.svg':'image/svg+xml','.wasm':'application/wasm','.mp4':'video/mp4','.wav':'audio/wav','.mp3':'audio/mpeg'};
const server=http.createServer((req,res)=>{let p=decodeURIComponent(new URL(req.url,'http://local').pathname).slice(1);if(!p||p.endsWith('/'))p+='index.html';if(!files.has(p)){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',mime[path.extname(p)]||'application/octet-stream');fs.createReadStream(path.join(root,p)).pipe(res);});
const evidence={sourceCommit:manifest.sourceCommit,matrix,routes:[],checks:0,failures:[],physicalDevices:false};
async function bounds(p,label){await p.waitForFunction(()=>[...document.querySelectorAll('.vnext-cosmos-scene')].every(e=>{const s=e.querySelector('.solar-scene');if(!s)return true;const r=e.getBoundingClientRect();if(!r.width||!r.height)return true;return Math.abs(Number(s.dataset.scale)-Math.min(r.width/800,r.height/560))<.002;}),null,{timeout:5000}).catch(()=>evidence.failures.push({label,type:'scene-resize-stale'}));await p.waitForTimeout(85);const result=await p.evaluate(()=>{
 const issues=[],view=document.documentElement.clientWidth;const rect=e=>e.getBoundingClientRect();const visible=e=>e.getClientRects().length&&getComputedStyle(e).visibility!=='hidden';
 if(document.documentElement.scrollWidth>view+1)issues.push({type:'overflow',width:document.documentElement.scrollWidth,view,elements:[...document.querySelectorAll('body *')].filter(visible).map(e=>({tag:e.tagName,id:e.id,cls:typeof e.className==='string'?e.className:'',right:rect(e).right,width:rect(e).width})).filter(e=>e.right>view+1&&e.width>0).slice(0,10)});
 for(const e of document.querySelectorAll('.site-global-header,.portrait-photo,.portrait-card,.depth-ladder,.depth-planner,.education-cards article,.project-card,.home-project,dialog[open],canvas:not(.scene-canvas):not(.vnext-cosmos-canvas)')){if(!visible(e))continue;const r=rect(e);if(r.width&& (r.left< -1||r.right>view+1))issues.push({type:'bounds',selector:e.id||e.className,left:r.left,right:r.right,view});}
 for(const svg of document.querySelectorAll('.solar-map')){const outer=rect(svg);if(!visible(svg)||!outer.width||!outer.height)continue;for(const e of svg.querySelectorAll('[data-solar-body],text')){const r=rect(e);if(!visible(e)||!r.width||!r.height)continue;if(r.left<outer.left-1||r.right>outer.right+1||r.top<outer.top-1||r.bottom>outer.bottom+1)issues.push({type:'solar-svg',tag:e.tagName});}}
 for(const v of document.querySelectorAll('.vnext-cosmos-scene')){const r=rect(v),scene=v.querySelector('.solar-scene');if(!scene||!visible(v)||!r.width||!r.height)continue;const scale=Number(scene.dataset.scale);for(const e of scene.querySelectorAll('.vnext-world,.vnext-cosmos-core')){const b=rect(e),glow=48*scale;if(b.left-glow<r.left-1||b.right+glow>r.right+1||b.top-glow<r.top-1||b.bottom+glow>r.bottom+1)issues.push({type:'solar-paint',left:b.left-r.left,right:b.right-r.left,width:r.width,glow});}}
 for(const e of document.querySelectorAll('.portrait-card,.depth-ladder button,.depth-planner,.education-cards article,.project-card,.home-project,.destination-card')){if(!visible(e))continue;const style=getComputedStyle(e);if(/hidden|clip/.test(style.overflow+style.overflowX+style.overflowY)&&(e.scrollWidth>e.clientWidth+2||e.scrollHeight>e.clientHeight+2))issues.push({type:'clipped-content',selector:e.className});}
 const controls=[...document.querySelectorAll('.global-controls>button,.global-controls [data-scene-audio]')];for(let i=0;i<controls.length;i++){const a=rect(controls[i]);if(a.width<43||a.height<43)issues.push({type:'tap-target',id:controls[i].id});for(let j=i+1;j<controls.length;j++){const b=rect(controls[j]);if(Math.min(a.right,b.right)-Math.max(a.left,b.left)>1&&Math.min(a.bottom,b.bottom)-Math.max(a.top,b.top)>1)issues.push({type:'control-collision'});}}
 return issues;});evidence.checks++;if(result.length)evidence.failures.push({label,issues:result});}
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;const browser=await chromium.launch({headless:true,executablePath:process.env.PORTFOLIO_BROWSER_EXECUTABLE,args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
try{const routes=[...files].filter(p=>p.endsWith('.html')&&(!process.env.RESPONSIVE_ROUTES||process.env.RESPONSIVE_ROUTES.split(',').includes(p)));for(const route of routes){const c=await browser.newContext();await c.route('https://**/*',r=>r.abort());const p=await c.newPage();p.on('pageerror',e=>evidence.failures.push({route,error:e.message}));await p.goto(base+'/'+route,{waitUntil:'domcontentloaded'});await p.waitForTimeout(200);for(const [width,height]of matrix){await p.setViewportSize({width,height});let dark;for(const theme of ['dark','light']){await p.evaluate(t=>window.PortfolioTheme?.setTheme(t,false),theme);await bounds(p,`${route} ${width}x${height} ${theme}`);const portrait=await p.locator('.portrait-photo img').count()?await p.locator('.portrait-photo img').first().boundingBox():null;if(theme==='dark')dark=portrait;else if(dark&&portrait)for(const key of ['x','y','width','height'])if(Math.abs(dark[key]-portrait[key])>1)evidence.failures.push({type:'hero-parity',route,width,key,dark:dark[key],light:portrait[key]});}
if(route==='learn.html'){const ladder=p.locator('.depth-ladder');if(!await ladder.isVisible())evidence.failures.push({type:'hidden-ladder',width});if(await ladder.locator('button').count()!==8)evidence.failures.push({type:'ladder-count',width});}}
console.log('CHECKED',route);evidence.routes.push(route);fs.writeFileSync(path.resolve(__dirname,'../docs/responsive-evidence/matrix.json'),JSON.stringify(evidence,null,2)+'\n');await c.close();}
const c=await browser.newContext();await c.route('https://**/*',r=>r.abort());const p=await c.newPage();for(const route of ['index.html','learn.html','projects.html','direction.html']){await p.goto(base+'/'+route,{waitUntil:'domcontentloaded'});for(let width=320;width<=1600;width+=37){await p.setViewportSize({width,height:850});await bounds(p,`live ${route} ${width}`);}}await c.close();
evidence.viewportChecksPassed=evidence.failures.length===0;evidence.zoom=[];for(const zoom of [.8,.9,1,1.1,1.25,1.5,2]){const profile=path.resolve(__dirname,'../staging/zoom-'+Date.now()+'-'+zoom);fs.mkdirSync(profile+'/Default',{recursive:true});fs.writeFileSync(profile+'/Default/Preferences',JSON.stringify({partition:{default_zoom_level:{x:Math.log(zoom)/Math.log(1.2)}}}));const z=await chromium.launchPersistentContext(profile,{headless:true,viewport:null,executablePath:process.env.PORTFOLIO_BROWSER_EXECUTABLE,args:['--window-size=1280,900']});await z.route('https://**/*',r=>r.abort());const page=z.pages()[0];for(const route of routes){await page.goto(base+'/'+route,{waitUntil:'domcontentloaded'});await bounds(page,`native zoom ${zoom} ${route}`);}const actual=await page.evaluate(()=>({dpr:devicePixelRatio,width:innerWidth,outerWidth}));if(Math.abs(actual.dpr-zoom)>=.02){evidence.nativeZoomFailure={requested:zoom,actual,reason:'Browser did not apply the requested native zoom'};await z.close();}assert(Math.abs(actual.dpr-zoom)<.02,'Native browser zoom must actually apply');evidence.zoom.push({zoom,...actual});await z.close();console.log('ZOOM',zoom);}
assert.deepEqual(evidence.failures,[]);console.log('PASS responsive matrix, continuous resize, solar paint bounds, header controls, hero parity and learning ladder.');
}finally{await browser.close();server.close();fs.mkdirSync(path.resolve(__dirname,'../docs/responsive-evidence'),{recursive:true});fs.writeFileSync(path.resolve(__dirname,'../docs/responsive-evidence/matrix.json'),JSON.stringify(evidence,null,2)+'\n');}})().catch(e=>{console.error(e);process.exitCode=1;server.close();});
