const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'../staging/website-2.0-runtime');
const manifest=JSON.parse(fs.readFileSync(path.resolve(__dirname,'../staging/website-2.0-runtime-manifest.json')));
const files=new Set(manifest.files.map(r=>r.path));
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.wasm':'application/wasm','.svg':'image/svg+xml','.mp4':'video/mp4','.wav':'audio/wav','.mp3':'audio/mpeg','.png':'image/png','.jpg':'image/jpeg'};
const server=http.createServer((req,res)=>{let rel=decodeURIComponent(new URL(req.url,'http://local').pathname).slice(1);if(!rel||rel.endsWith('/'))rel+='index.html';if(!files.has(rel)){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',mime[path.extname(rel)]||'application/octet-stream');res.end(fs.readFileSync(path.join(root,rel)));});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch({headless:true,executablePath:process.env.PORTFOLIO_BROWSER_EXECUTABLE,args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});const evidence={sourceCommit:manifest.sourceCommit,routes:[],viewports:[],failures:[],physicalHardware:false};
try{
 for(const route of [...files].filter(p=>p.endsWith('.html'))){const context=await browser.newContext({viewport:{width:1440,height:1000}});const p=await context.newPage();p.on('pageerror',e=>evidence.failures.push(`${route}: ${e.message}`));p.on('response',r=>{if(r.url().startsWith(base)&&r.status()>=400)evidence.failures.push(`${route}: ${r.status()} ${r.url()}`);});await p.goto(base+'/'+route,{waitUntil:'domcontentloaded'});await p.waitForTimeout(350);const ids=await p.locator('[id]').evaluateAll(es=>es.map(e=>e.id));if(ids.length!==new Set(ids).size)evidence.failures.push(route+': duplicate IDs');if(!route.startsWith('games/'))for(const [width,height]of [[320,740],[390,844],[820,1180],[1180,820],[1440,1000],[1920,1080],[844,390]]){await p.setViewportSize({width,height});for(const theme of ['dark','light']){await p.evaluate(t=>window.PortfolioTheme?.setTheme(t,false),theme);try{await p.waitForFunction(()=>document.documentElement.scrollWidth<=innerWidth+1,null,{timeout:1500});}catch{evidence.failures.push(`${route}: overflow ${width} ${theme}`);}}}evidence.routes.push(route);await context.close();}
 const context=await browser.newContext(),p=await context.newPage();for(const [w,h]of [[1440,1000],[1920,1080],[820,1180],[1180,820],[390,844],[320,740],[844,390]]){await p.setViewportSize({width:w,height:h});await p.goto(base+'/',{waitUntil:'domcontentloaded'});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`overflow ${w}`);await p.locator('.skip').focus();assert(await p.locator('.skip').evaluate(e=>e===document.activeElement));await p.keyboard.press('Enter');await p.locator('#menu').click();assert.equal(await p.locator('#menu').getAttribute('aria-expanded'),'true');await p.keyboard.press('Escape');assert.equal(await p.locator('#menu').getAttribute('aria-expanded'),'false');assert(await p.locator('#menu').evaluate(e=>e===document.activeElement));evidence.viewports.push([w,h]);}
 for(const forbidden of ['/tests/site.test.mjs','/docs/WEBSITE-2.0-AUDIT.md','/Z:/public_html/index.html','/Index.html'])assert.equal((await p.request.get(base+forbidden)).status(),404);
 const index=await (await p.request.get(base+'/deep-learning/index.json')).json();assert.equal(new Set(Object.values(index)).size,76);for(const chunk of new Set(Object.values(index)))assert.equal((await p.request.get(base+'/deep-learning/'+chunk)).status(),200);
 await p.goto(base+'/index.html',{waitUntil:'domcontentloaded'});await p.locator('[data-solar=portfolio]').scrollIntoViewIfNeeded();await p.waitForTimeout(300);await p.locator('[data-solar=portfolio]').screenshot({path:path.resolve(__dirname,'../docs/phase3-evidence/home-solar.png'),animations:'disabled'});await p.goto(base+'/learn.html',{waitUntil:'domcontentloaded'});await p.locator('[data-solar=learning]').scrollIntoViewIfNeeded();await p.waitForTimeout(300);await p.locator('[data-solar=learning]').screenshot({path:path.resolve(__dirname,'../docs/phase3-evidence/learn-solar.png'),animations:'disabled'});await context.close();assert.deepEqual(evidence.failures,[]);console.log(`PASS isolated ${evidence.routes.length} routes, 7 viewports, 76 lazy chunks, strict case and outside-root denials.`);
}finally{await browser.close();server.close();fs.mkdirSync(path.resolve(__dirname,'../docs/phase3-evidence'),{recursive:true});fs.writeFileSync(path.resolve(__dirname,'../docs/phase3-evidence/runtime-browser.json'),JSON.stringify(evidence,null,2)+'\n');}
})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
