const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');const {chromium}=require('playwright');
const root=path.resolve(process.env.PORTFOLIO_RUNTIME_ROOT||'staging/website-2.0-runtime'),mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.png':'image/png','.webp':'image/webp','.jpg':'image/jpeg'};
const output=path.resolve(process.env.PORTFOLIO_QA_DIR||'visual-qa/refinement');fs.mkdirSync(output,{recursive:true});const result={errors:[],checks:[],physicalDevices:false};
const server=http.createServer((req,res)=>{const f=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(!f.startsWith(root+'/'))return res.writeHead(403).end();try{res.setHeader('Content-Type',mime[path.extname(f)]||'application/octet-stream');fs.createReadStream(f).on('error',()=>res.writeHead(404).end()).pipe(res)}catch{res.writeHead(404).end()}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}/`,browser=await chromium.launch({headless:true,executablePath:process.env.PORTFOLIO_BROWSER_EXECUTABLE,args:['--no-sandbox']});try{
 const p=await browser.newPage({viewport:{width:390,height:844}});await p.route('https://**/*',r=>r.abort());p.on('pageerror',e=>result.errors.push(e.message));await p.goto(base+'security-research.html');assert.equal(await p.locator('#security-export').isEnabled(),false);
 await p.locator('#vuln-input').fill('../lab-secret.txt');await p.locator('#vuln-run').click();assert.match(await p.locator('#vuln-output').textContent(),/Virtual root boundary escape reproduced/);result.checks.push('controlled virtual path finding');
 await p.locator('#fuzz-iterations').fill('100');await p.locator('#fuzz-run').click();const fuzz=await p.locator('#fuzz-output').textContent();assert.match(fuzz,/Minimized failing input/);await p.locator('#fuzz-run').click();assert.equal(await p.locator('#fuzz-output').textContent(),fuzz);await p.locator('#fuzz-iterations').fill('100.5');await p.locator('#fuzz-run').click();assert.match(await p.locator('#fuzz-output').textContent(),/whole iterations/);result.checks.push('deterministic fuzzer and invalid iteration count');
 for(const tool of ['linux','ad','container','surface']){await p.locator('#'+tool+'-run').click();assert(await p.locator('#'+tool+'-output .security-finding').count()>0,tool+' sample generates findings');}
 const dl=await Promise.all([p.waitForEvent('download'),p.locator('#security-export').click()]);const payload=JSON.parse(fs.readFileSync(await dl[0].path(),'utf8'));assert.equal(payload.tool,'attack-surface-inventory');assert(payload.findings.length>0);result.checks.push('six local tools and matching JSON export');
 await p.locator('#surface-input').fill('test,not-a-port,https,internet,on,current');assert.equal(await p.locator('#security-export').isEnabled(),false);await p.locator('#surface-run').click();assert.match(await p.locator('#surface-output').textContent(),/whole port/);assert.equal(await p.locator('#security-export').isEnabled(),false);
 await p.locator('#linux-input').fill('null');await p.locator('#linux-run').click();assert.match(await p.locator('#linux-output').textContent(),/nonempty JSON object/);await p.locator('#linux-input').fill('{"files":"invalid"}');await p.locator('#linux-run').click();assert.match(await p.locator('#linux-output').textContent(),/array with valid entries/);
 await p.locator('#container-input').fill('{"privileged":"false"}');await p.locator('#container-run').click();assert.match(await p.locator('#container-output').textContent(),/true or false/);
 await p.locator('#ad-input').fill('{"start":"Domain Admins","targets":["Domain Admins"],"edges":[]}');await p.locator('#ad-run').click();assert.match(await p.locator('#ad-output').textContent(),/already a protected target/);result.checks.push('invalid schemas/ports cannot export stale findings; zero-edge target detected');
 await p.goto(base+'agent-workbench.html');await p.locator('#agent-goal').fill('Review one bounded local experiment');await p.locator('#agent-form button[type=submit]').click();await p.locator('#agent-goal').fill('Review the revised local experiment');const ledgerDownload=await Promise.all([p.waitForEvent('download'),p.locator('#agent-export').click()]);const ledger=JSON.parse(fs.readFileSync(await ledgerDownload[0].path(),'utf8'));assert.equal(ledger.goal,'Review the revised local experiment');assert(ledger.requiresApproval);await p.locator('#agent-goal').fill('');await p.locator('#agent-export').click();assert.equal(await p.locator('#agent-status').textContent(),'A goal is required');result.checks.push('MIND export recomputes current inputs and handles empty goal');
 assert.deepEqual(result.errors,[]);result.passed=true;console.log('PASS Security Research: six controlled local tools, deterministic replay, invalid-input recovery, accurate current-result export and MIND ledger export.');
}finally{fs.writeFileSync(path.join(output,'security-journeys.json'),JSON.stringify(result,null,2));await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1});
