const $=s=>document.querySelector(s);
function rng(seed){let x=(Number(seed)||1)>>>0;return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967296}}
function create(n,p,seed){const r=rng(seed),edges=[],freq=Array.from({length:n},()=>-.8+r()*1.6),phase=Array.from({length:n},()=>r()*Math.PI*2);for(let i=0;i<n;i++)for(let j=i+1;j<n;j++)if(r()<p)edges.push([i,j]);return {n,edges,freq,phase,step:0,seed}}
function advance(g,steps=100,coupling=1.2,dt=.02){const nbr=Array.from({length:g.n},()=>[]);g.edges.forEach(([a,b])=>{nbr[a].push(b);nbr[b].push(a)});for(let k=0;k<steps;k++){const next=g.phase.slice();for(let i=0;i<g.n;i++){let influence=0;for(const j of nbr[i])influence+=Math.sin(g.phase[j]-g.phase[i]);next[i]+=dt*(g.freq[i]+coupling*(influence/(nbr[i].length||1)));}g.phase=next.map(x=>((x%(Math.PI*2))+Math.PI*2)%(Math.PI*2));g.step++}return g}
function order(g){const z=g.phase.reduce((s,p)=>[s[0]+Math.cos(p),s[1]+Math.sin(p)],[0,0]);return Math.hypot(...z)/g.n}
let g,selected=-1,running=false;
function draw(){const c=$('#network-chart'),ctx=c.getContext('2d'),d=devicePixelRatio||1,w=c.clientWidth,h=Math.min(620,Math.max(300,w*.68));c.width=w*d;c.height=h*d;ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,w,h);const pts=g.phase.map((p,i)=>({x:w/2+Math.cos(p)*(w*.32),y:h/2+Math.sin(p)*(h*.38),i}));ctx.lineWidth=1;g.edges.forEach(([a,b])=>{ctx.strokeStyle='#354044';ctx.beginPath();ctx.moveTo(pts[a].x,pts[a].y);ctx.lineTo(pts[b].x,pts[b].y);ctx.stroke()});pts.forEach(pt=>{ctx.fillStyle=pt.i===selected?'#f4a575':'#8cc8d1';ctx.beginPath();ctx.arc(pt.x,pt.y,pt.i===selected?8:5,0,Math.PI*2);ctx.fill()});$('#network-status').textContent=`Step ${g.step} · order parameter R = ${order(g).toFixed(4)} · ${g.edges.length} edges`}
function render(){g=create(Number($('#nodes').value),Number($('#density').value),Number($('#network-seed').value));draw();$('#node-detail').textContent='Click a node to inspect its phase and neighbors.';window.__emergent=g}
function tick(){if(!running)return;advance(g,1,Number($('#coupling').value));draw();requestAnimationFrame(tick)}
$('#network-controls').addEventListener('submit',e=>{e.preventDefault();running=false;render()});$('#step-network').addEventListener('click',()=>{advance(g,100,Number($('#coupling').value));draw()});$('#run-network').addEventListener('click',()=>{running=!running;$('#run-network').textContent=running?'Pause':'Start';if(running)tick()});$('#export-network').addEventListener('click',()=>{const b=new Blob([JSON.stringify({...g,coupling:Number($('#coupling').value)},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='emergent-systems-experiment.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)});$('#network-chart').addEventListener('click',e=>{const r=$('#network-chart').getBoundingClientRect(),w=r.width,h=r.height,pts=g.phase.map((p,i)=>({x:w/2+Math.cos(p)*(w*.32),y:h/2+Math.sin(p)*(h*.38),i}));const hit=pts.map(x=>({...x,d:Math.hypot(x.x-(e.clientX-r.left),x.y-(e.clientY-r.top))})).sort((a,b)=>a.d-b.d)[0];if(hit&&hit.d<24){selected=hit.i;const neighbors=[];g.edges.forEach(([a,b])=>{if(a===selected)neighbors.push(b);if(b===selected)neighbors.push(a)});$('#node-detail').textContent=`Node ${selected}: phase ${(g.phase[selected]%(Math.PI*2)).toFixed(3)} rad · intrinsic frequency ${g.freq[selected].toFixed(3)} · neighbors ${neighbors.join(', ')||'none'}`;draw()}});addEventListener('resize',draw);render();
export {create,advance,order};
