const $=s=>document.querySelector(s);
function rng(seed){let x=(Number(seed)||1)>>>0;return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967296}}
function order(g){const z=g.phase.reduce((s,p)=>[s[0]+Math.cos(p),s[1]+Math.sin(p)],[0,0]);return Math.hypot(...z)/g.n}
function create(n,p,seed){const r=rng(seed),edges=[],freq=Array.from({length:n},()=>-.8+r()*1.6),phase=Array.from({length:n},()=>r()*Math.PI*2),pos=[];for(let i=0;i<n;i++){const a=2*Math.PI*i/n+(r()-.5)*.12,rad=.34+r()*.13;pos.push({x:.5+Math.cos(a)*rad,y:.43+Math.sin(a)*rad*.78})}for(let i=0;i<n;i++)for(let j=i+1;j<n;j++)if(r()<p)edges.push([i,j]);const g={n,edges,freq,phase,pos,step:0,seed,history:[]};g.history.push(order(g));return g}
function advance(g,steps=100,coupling=1.2,dt=.02){const nbr=Array.from({length:g.n},()=>[]);g.edges.forEach(([a,b])=>{nbr[a].push(b);nbr[b].push(a)});for(let k=0;k<steps;k++){const next=g.phase.slice();for(let i=0;i<g.n;i++){let influence=0;for(const j of nbr[i])influence+=Math.sin(g.phase[j]-g.phase[i]);next[i]+=dt*(g.freq[i]+coupling*(influence/(nbr[i].length||1)))}g.phase=next.map(x=>((x%(Math.PI*2))+Math.PI*2)%(Math.PI*2));g.step++;if(g.step%4===0){g.history.push(order(g));if(g.history.length>240)g.history.shift()}}return g}
let g,selected=-1,running=false;
function draw(){const c=$('#network-chart'),ctx=c.getContext('2d'),d=Math.min(devicePixelRatio||1,2),w=Math.max(280,c.clientWidth),h=Math.min(650,Math.max(360,w*.7));c.width=w*d;c.height=h*d;ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,w,h);ctx.fillStyle='rgba(255,255,255,.015)';ctx.fillRect(0,0,w,h);const chartH=h-86,pts=g.pos.map((p,i)=>({x:p.x*w,y:p.y*chartH+22,i}));ctx.lineWidth=1;g.edges.forEach(([a,b])=>{ctx.strokeStyle=(a===selected||b===selected)?'#6fc9d7':'#354044';ctx.beginPath();ctx.moveTo(pts[a].x,pts[a].y);ctx.lineTo(pts[b].x,pts[b].y);ctx.stroke()});pts.forEach(pt=>{const phase=g.phase[pt.i],hue=(phase/(Math.PI*2))*360;ctx.fillStyle=pt.i===selected?'#f4a575':`hsl(${hue} 68% 62%)`;ctx.shadowColor=ctx.fillStyle;ctx.shadowBlur=pt.i===selected?14:6;ctx.beginPath();ctx.arc(pt.x,pt.y,pt.i===selected?9:6,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle='#e8f8fb77';ctx.beginPath();ctx.moveTo(pt.x,pt.y);ctx.lineTo(pt.x+Math.cos(phase)*12,pt.y+Math.sin(phase)*12);ctx.stroke()});const y0=h-60;ctx.strokeStyle='#354044';ctx.strokeRect(8,y0,w-16,48);if(g.history.length>1){ctx.strokeStyle='#8cc8d1';ctx.lineWidth=2;ctx.beginPath();g.history.forEach((v,i)=>{const x=10+(w-20)*i/Math.max(1,g.history.length-1),y=y0+45-v*42;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}ctx.fillStyle='#a7b1b3';ctx.font='11px sans-serif';ctx.fillText('order parameter R history',13,y0+13);$('#network-status').textContent=`Step ${g.step.toLocaleString()} · R = ${order(g).toFixed(4)} · ${g.edges.length} edges · seed ${g.seed}`}
function render(){running=false;$('#run-network').textContent='Start';selected=-1;g=create(Number($('#nodes').value),Number($('#density').value),Number($('#network-seed').value));draw();$('#node-detail').textContent='Select a node to inspect phase, intrinsic frequency and declared neighbors.';window.__emergent=g}
function tick(){if(!running)return;if(document.hidden){requestAnimationFrame(tick);return}advance(g,1,Number($('#coupling').value));draw();requestAnimationFrame(tick)}
if(typeof document!=='undefined'){$('#network-controls').addEventListener('submit',e=>{e.preventDefault();render()});$('#step-network').addEventListener('click',()=>{advance(g,100,Number($('#coupling').value));draw()});$('#run-network').addEventListener('click',()=>{running=!running;$('#run-network').textContent=running?'Pause':'Start';if(running)tick()});$('#export-network').addEventListener('click',()=>{const b=new Blob([JSON.stringify({...g,coupling:Number($('#coupling').value),orderParameter:order(g)},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='emergent-systems-experiment.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)});$('#network-chart').addEventListener('click',e=>{const r=$('#network-chart').getBoundingClientRect(),w=r.width,h=r.height,chartH=h-86,pts=g.pos.map((p,i)=>({x:p.x*w,y:p.y*chartH+22,i}));const hit=pts.map(x=>({...x,d:Math.hypot(x.x-(e.clientX-r.left),x.y-(e.clientY-r.top))})).sort((a,b)=>a.d-b.d)[0];if(hit&&hit.d<26){selected=hit.i;const neighbors=[];g.edges.forEach(([a,b])=>{if(a===selected)neighbors.push(b);if(b===selected)neighbors.push(a)});$('#node-detail').textContent=`Node ${selected}: phase ${g.phase[selected].toFixed(3)} rad · intrinsic frequency ${g.freq[selected].toFixed(3)} · degree ${neighbors.length} · neighbors ${neighbors.join(', ')||'none'}`;draw()}});addEventListener('resize',()=>g&&draw());render();}
export {create,advance,order};