"""Generate dedicated section/subject pages from existing biography and real corpus."""
import html,json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
E=html.escape
def main():
    home=(ROOT/'index.html').read_text(encoding='utf-8');header=re.search(r'<header\b.*?</header>',home,re.S).group()
    data=json.loads((ROOT/'knowledge-data.js').read_text(encoding='utf-8').split('=',1)[1].strip().rstrip(';'))
    def page(path,title,body,extra=''):
        text='<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><script src="site-theme.js"></script><title>'+E(title)+' | Joshua Randall</title><link rel="icon" href="assets/favicon.svg"><link rel="stylesheet" href="styles.css"><link rel="stylesheet" href="site-resilience.css"><link rel="stylesheet" href="site-scenes.css"><link rel="stylesheet" href="site-sections.css"><script defer src="site-navigation.js"></script><script defer src="site-search.js"></script><script defer src="site-scenes.js"></script><script defer src="site-resilience.js"></script>'+extra+'</head><body class="destination-page"><a class="skip" href="#main">Skip to content</a>'+header+'<main id="main" class="wrap"><h1>'+E(title)+'</h1>'+body+'</main><footer class="wrap"><a href="index.html">Joshua Randall</a><button data-scene-motion>Pause animations</button></footer><dialog id="search-dialog" aria-labelledby="search-title"><h2 id="search-title">Explore the portfolio</h2><button data-close aria-label="Close search">Close</button><label for="search-input">Search sections, projects and lessons</label><input id="search-input" type="search"><div id="search-results"></div></dialog></body></html>'
        (ROOT/path).write_text(text,encoding='utf-8')
    for name,title in [('about','About Me'),('direction','Direction')]:
        section=re.search(r'<section\b[^>]*\bid="'+name+r'"[^>]*>.*?</section>',home,re.S)
        if not section and name=='about':
            intro=re.search(r'<p class="hero-intro">.*?</p>',home,re.S).group()
            page('about.html',title,intro+'<p>25+ years in technology. Oregon State University.</p><p><a href="expertise-experience.html">Explore my expertise and experience</a> · <a href="resume.html">Résumé and downloads</a> · <a href="direction.html">Where I am heading</a></p>')
        elif section:page(name+'.html',title,section.group())
        else:raise ValueError('Missing original biography section '+name)
    domains=[]
    for domain in data['domains']:
        lessons=[l for l in data['lessons'] if l['domain']==domain['id']]
        domains.append({'id':domain['id'],'title':domain['name'],'summary':domain['short'],'lessons':[{'id':l['id'],'title':l['title'],'level':l.get('level',''),'type':l.get('type',''),'category':l['category']} for l in lessons]})
        body='<p class="hero-intro">'+E(domain['short'])+'</p><p>'+str(len(lessons))+' learning records across '+str(len({l['category'] for l in lessons}))+' categories. Choose a level and build a plan that fits your next goal.</p><section><h2>Your subject plan</h2><label for="subject-level">Progression level</label><select id="subject-level"><option value="">All supported levels</option></select> <label for="subject-type">Activity</label><select id="subject-type"><option value="">Lessons, labs and practice</option></select><p><button id="save-subject-plan">Save selected lessons</button> <button id="clear-subject-plan">Clear plan</button></p><p id="subject-status" role="status"></p><div id="subject-lessons" class="destination-grid"></div><button id="subject-more">Show more</button></section><section><h2>Explore and verify</h2><p>Every lesson opens on its own route with its available explanation, lab, practice, and evidence views. Published depth varies; a plan does not imply research mastery or verified completion.</p><div class="destination-grid">'+''.join('<a class="destination-card" href="'+href+'">'+label+'</a>' for href,label in [('learn-browse.html?domain='+domain['id'],'Browse all subject lessons'),('learn-labs.html?domain='+domain['id'],'Labs and interactives'),('learn-practice.html?domain='+domain['id'],'Practice'),('learn-verify.html?domain='+domain['id'],'Verification and evidence'),('learn-mastery.html?domain='+domain['id'],'Progression and mastery')])+'</div></section>'
        page('learn-'+domain['id']+'.html',domain['name'],body,'<script defer src="site-subject.js" data-domain="'+domain['id']+'"></script>')
    (ROOT/'assets/site-subjects.json').write_text(json.dumps({'domains':domains},ensure_ascii=False,separators=(',',':'))+'\n',encoding='utf-8')
    approaches=[
      ('Geometric AI','Learn from distances, directions and symmetries.','Vectors, manifolds, invariant transformations','Implement nearest-neighbor geometry; compare rotated inputs.','Add equivariant representations and measure out-of-distribution error.','Geometry alone does not supply semantic understanding.','project-geometric-ai.html'),
      ('LLM AI','Predict and generate token sequences from learned context.','Conditional probability, attention, optimization','Build a tiny token predictor and held-out loss evaluator.','Add retrieval, tool boundaries and task-specific evaluation.','Fluent output may be false; verify factual claims.','learn-browse.html?q=language'),
      ('Agentic AI','Use a model inside a bounded observe-plan-act loop.','State machines, planning, partial observability','Create a deterministic tool-using agent in a local sandbox.','Add approval gates, budgets, recovery and replayable traces.','Tool errors and unchecked actions compound.','agent-workbench.html'),
      ('Machine Learning','Fit a predictive function from examples.','Linear algebra, probability, empirical risk','Train a linear classifier with a held-out split.','Compare calibrated models across shifting data distributions.','Training accuracy is not evidence of generalization.','learn-browse.html?q=learning'),
      ('Deep Learning','Compose trainable layers to learn representations.','Chain rule, gradients, nonlinear functions','Implement a small multilayer network and gradient checks.','Add regularization and profile training/inference costs.','Data quality, compute and distribution shift limit performance.','learn-browse.html?q=gradient'),
      ('Reinforcement Learning','Learn actions from rewards and transitions.','Markov decision processes, value functions','Implement tabular Q-learning in a grid environment.','Compare policy optimization with constrained rewards.','Reward hacking and unsafe exploration require explicit tests.','learn-browse.html?q=probability'),
      ('Computer Vision','Infer structure from images or video.','Convolution, geometry, sampling','Build an image classifier with an explicit train/test split.','Extend to detection and evaluate occlusion and lighting shifts.','Visual correlations can fail outside the training setting.','learn-browse.html?q=image'),
      ('Graph Neural Networks','Exchange learned messages along graph edges.','Graph theory, permutation symmetry','Implement message passing and node classification.','Test deeper models, graph sampling and unseen graph families.','Oversmoothing and graph leakage can mislead evaluation.','learn-browse.html?q=graph'),
      ('Multimodal AI','Connect representations from different input types.','Alignment, embeddings, fusion','Match paired text/image embeddings on a small dataset.','Compare early and late fusion under missing modalities.','One modality can dominate or hide contradictions.','learn-browse.html?q=vector'),
      ('Generative AI','Model distributions to produce new samples.','Likelihood, latent variables, sampling','Build a character generator and inspect held-out behavior.','Compare latent and iterative generation with diversity checks.','Novel samples do not guarantee accuracy or originality.','learn-browse.html?q=probability'),
      ('Symbolic AI','Represent explicit facts and apply rules or search.','Logic, constraints, search','Build a rule engine with traceable conclusions.','Add constraint solving and conflict explanations.','Rules need maintenance and struggle with noisy inputs.','learn-browse.html?q=logic'),
      ('Neuro-symbolic AI','Combine learned representations with explicit constraints.','Logic plus differentiable models','Use a classifier followed by a validated rule layer.','Compare constraint-guided training and symbolic planning.','The interface can inherit failures from both components.','learn-browse.html?q=logic'),
      ('Multi-agent systems','Coordinate agents with separate state and roles.','Communication protocols, game theory','Simulate cooperating agents with logged messages.','Evaluate contention, adversarial messages and shared-resource limits.','More agents can amplify correlated mistakes.','learn-browse.html?q=distributed'),
      ('Game AI','Choose actions within game rules and objectives.','Search trees, heuristics, utility','Build minimax with legal-move validation.','Add pruning, evaluation tuning and strength benchmarks.','Stronger play must still preserve deterministic legal state.','project-battle-chess.html'),
      ('Embodied / Robotic AI','Connect perception, planning and physical control.','Kinematics, estimation, feedback control','Simulate a controller with sensor noise.','Add planning and test latency, collisions and recovery.','Simulation success does not establish hardware safety.','learn-browse.html?q=control'),
      ('AI memory / retrieval','Retrieve relevant stored context for a task.','Indexing, similarity, ranking','Build a document index with cited retrieval results.','Compare hybrid retrieval and memory expiry policies.','Stale or irrelevant context can corrupt downstream answers.','learn-browse.html?q=search'),
      ('Build Your Own AI','Assemble a small system with measurable boundaries.','Data, model, interface, evaluation','Choose one task and implement a reproducible baseline.','Add complexity only when held-out evidence improves.','A demo is not an evaluated production system.','learn-advanced.html'),
      ('Project MIND','Explore agent workbench and personal knowledge architecture.','State, memory, task contracts','Use the existing workbench to inspect bounded task flow.','Extend persistent memory with provenance and review gates.','Keep speculative capabilities separate from implemented behavior.','project-mind.html'),
      ('Personal development agent','A future assistant for Joshua’s goals and learning plans.','Preference modeling, planning, privacy','Start with a user-reviewed plan and local progress log.','Add retrieval and suggestions with explicit action authorization.','Future design; no autonomous personal agent is claimed here.','learn.html')]
    body='<p class="hero-intro">Understand the approaches, build small systems, and evaluate what they actually do.</p><p>These implementation paths establish the AI section. Existing labs and learning records are linked below; proposed advanced implementations remain future work.</p><div class="destination-grid">'
    for title,definition,math,minimal,advanced,limit,link in approaches:
        body+='<article class="destination-card"><h2>'+E(title)+'</h2><p>'+E(definition)+'</p><dl><dt>Foundations</dt><dd>'+E(math)+'</dd><dt>Minimal build</dt><dd>'+E(minimal)+'</dd><dt>Advanced architecture and evaluation</dt><dd>'+E(advanced)+'</dd><dt>Limits to test</dt><dd>'+E(limit)+'</dd></dl><a href="'+link+'">Explore related project or foundations →</a></article>'
    page('ai-development.html','AI Development',body+'</div>')
    game=(ROOT/'game-development.html').read_text(encoding='utf-8')
    if 'id="engine-path"' not in game:
        topics=['Future Games','Custom Game Engine Development','Game AI','Graphics & Rendering','Physics','Animation','Procedural Generation','Technical Art','Audio','Multiplayer','Engine Architecture']
        body='<section id="engine-path" class="wrap"><h2>Build the worlds behind the games</h2><p>Keep current releases independent while developing a Joshua-owned engine architecture. The full engine is future work.</p><div class="destination-grid">'+''.join('<article class="destination-card"><h3>'+E(t)+'</h3><p>'+('Planned releases will appear here when playable.' if t=='Future Games' else 'Explore the design, build a minimal subsystem, then verify behavior and performance before integration.')+'</p><a href="'+('engine-development.html' if 'Engine' in t else 'learn-browse.html?q='+t.replace(' ','%20'))+'">Explore this path →</a></article>' for t in topics)+'</div></section>'
        game=game.replace('</main>',body+'</main>').replace('</head>','<link rel="stylesheet" href="site-sections.css"></head>');(ROOT/'game-development.html').write_text(game,encoding='utf-8')
    page('engine-development.html','Custom Game Engine Development','<p class="hero-intro">Own the interfaces. Keep games shipping.</p><section><h2>Future architecture</h2><p>The engine is a planned project, not a replacement for the working Godot export or Crown &amp; Ash runtime.</p><ol><li>Platform adapters: windows, input, clocks and filesystem.</li><li>Joshua-owned scene, entity, asset and save formats with documented versioning.</li><li>Renderer, physics and audio interfaces behind replaceable adapters.</li><li>Deterministic simulation, replay and headless tests.</li><li>Editor and build pipeline separated from the runtime.</li></ol><h2>Ownership and commercial use</h2><p>Keep original engine architecture, source and formats under Joshua’s control. Prefer permissively licensed dependencies after reviewing their actual license and redistribution obligations. Third-party code retains its own ownership and notices; an adapter does not change its license.</p><h2>Integration gates</h2><p>Prototype one subsystem, measure performance, verify asset round trips, and test compatibility before a game adopts it. No full engine build is part of this phase.</p><a href="game-development.html">Return to Game Development</a></section>')
    print('Generated About, Direction, AI, engine design and',len(domains),'corpus-backed subject destinations.')
if __name__=='__main__':main()
