'use strict';
const $=id=>document.getElementById(id),G=GeoMath;
const state={tab:'geometry',shape:'torus',n:1200,scale:1,noise:0,seed:42,inverseSeed:42,k:30,display:'reference',modelCase:0,modelDisplay:'gnp',radius:1,D:.2,time:0,sigma:.12,count:8,gbShape:'torus',gbN:1200,gbNoise:0,gbK:30,gbDisplay:'reference',spectrumL:2,spectrumR:1,flowR0:1.4,flowTime:0};
let dataset,values=[],baseline=null,baselineGeometry=null,worker=null,job=0,angleY=.5,angleX=-.35,zoom=1,spinning=false,playing=false,lastTime=0,dirty=true,posterior=null,storedImport=null,gbDataset=null,gbGeometry=null,selectedIndex=null,projectedCache=[];
const labels={geometry:'Surface explorer',models:'Neural operators',diffusion:'Surface diffusion',topology:'Topology test',spectrum:'Spectral geometry',flow:'Curvature flow',inverse:'Shape detective'};
const titleCase=s=>s.charAt(0).toUpperCase()+s.slice(1),fmt=(n,d=3)=>Number.isFinite(n)?n.toFixed(d):'—';
const status=s=>{$('status').textContent=s};
const escapeHtml=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function field(id,label,html,full=false){return `<div class="field ${full?'full':''}"><label for="${id}">${label}</label>${html}</div>`}
function select(id,opts,val){return `<select id="${id}">${opts.map(([v,t])=>`<option value="${v}" ${String(v)===String(val)?'selected':''}>${t}</option>`).join('')}</select>`}
function range(id,label,min,max,step,value,unit=''){return field(id,`${label}<output id="${id}-value">${value}${unit}</output>`,`<input id="${id}" type="range" min="${min}" max="${max}" step="${step}" value="${value}">`)}
function metrics(items){$('metrics').innerHTML=items.map(([label,val])=>`<div class="metric"><span>${label}</span><strong>${val}</strong></div>`).join('')}
function explain(title,body){$('explain-title').textContent=title;$('explain-body').innerHTML=body}
function controls(){
 const t=state.tab;
 $('mode-kicker').textContent=labels[t]?.toUpperCase()||'';
 if(t==='geometry'){
 $('mode-title').textContent='The shape of a surface';
 $('control-body').innerHTML=field('shape','Surface',select('shape',[['torus','Torus'],['sphere','Sphere'],['saddle','Saddle'],...(storedImport?[['upload','Your point cloud']]:[])],state.shape))+field('density','Sample points',select('density',[[600,'600'],[1200,'1,200'],[2200,'2,200']],state.n))+range('scale','Size',.6,1.6,.1,state.scale)+range('noise','Noise σ',0,.04,.005,state.noise)+field('display','Color by',select('display',[['reference','Reference K'],['estimate','Estimated K'],['mean','Estimated |H|'],['kmax','Principal |κ|max'],['kmin','Principal |κ|min'],['residual','Fit residual'],['error','Absolute K error']],state.display))+field('neighbors','Neighborhood',select('neighbors',[[20,'20 points'],[30,'30 points'],[50,'50 points']],state.k))+`<button class="wide primary" id="estimate">Estimate curvature</button><p class="small">Runs a local polynomial fit on this device. Noise is a fraction of the size setting.</p><div class="control-divider"></div><details class="import-panel"><summary>Import your geometry</summary>`+field('upload','Choose a point cloud','<input type="file" id="upload" accept=".xyz,.csv,.obj,.json">',true)+`<p class="small">XYZ / CSV coordinates, OBJ vertices, or exported GNP JSON. Files stay on your device. Maximum 2 MB; larger point sets are sampled to 2,200 points.</p></details><button class="wide" id="export-points">Export point cloud</button>`;
 for(const id of ['shape','density','scale','noise','neighbors'])$(id).oninput=()=>{const keys={shape:'shape',density:'n',scale:'scale',noise:'noise',neighbors:'k'},key=keys[id];state[key]=id==='shape'?$(id).value:Number($(id).value);if($(id+'-value'))$(id+'-value').textContent=state[key];invalidate();updateGeometry()};
 $('display').onchange=()=>{state.display=$('display').value;const needs=['estimate','mean','kmax','kmin','residual','error'].includes(state.display);if(needs&&!baselineGeometry)runEstimate();else updateGeometry()};
 $('estimate').onclick=runEstimate;$('upload').onchange=importCloud;$('export-points').onclick=()=>download('geometry-points.csv','x,y,z\n'+dataset.points.map(p=>p.join(',')).join('\n'),'text/csv');
 explain('A donut has two kinds of bend.',`<p>On the outside of a torus, the surface bends the same way in both principal directions. On the inside, it bends in opposite directions, like a saddle. Gaussian curvature multiplies these two principal curvatures, so its sign distinguishes the two regions.</p><details><summary>Try an experiment</summary><p>Choose the sphere. Estimate curvature with no noise, then increase coordinate noise. Compare the error and change the neighborhood size. A larger neighborhood averages more data but can blur local shape. Predict what doubling a sphere’s radius would do to its Gaussian curvature.</p></details><details><summary>What the colors measure</summary><p>K = 1/r² for a sphere. For a torus, K = cos(v) / [r(R + r cos(v))], with major radius R = 1.35 × size and tube radius r = 0.5 × size. Units are arbitrary length units. The analytic reference belongs to the underlying clean surface at each sampled location, even when observed coordinates are noisy.</p></details><details><summary>How the estimate works</summary><p>A principal-component frame defines a local tangent plane. A weighted quadratic surface is fitted to the nearest points; its derivatives give Gaussian curvature. This conventional numerical baseline is not a neural network. Sparse regions, edges, sharp corners, or large noise can give unreliable values. Uploaded surfaces have no analytic ground truth.</p></details>`);
 } else if(t==='models'){
 const cases=window.GNP_BENCHMARKS?.cases||[];
 $('mode-title').textContent='Measure a learned operator';
 $('control-body').innerHTML=field('case','Recorded experiment',select('case',cases.map((c,i)=>[i,c.label]),state.modelCase),true)+field('model-display','Color by',select('model-display',[['gnp','GNP prediction'],['reference','Analytic reference'],['baseline','Local quadratic fit'],['error','GNP absolute error']],state.modelDisplay),true)+`<p class="small">Actual pretrained-model outputs, computed in Python and bundled with this lab. Switching cases loads a saved experiment; it does not rerun the network.</p><div class="control-divider"></div><button class="wide" id="export-case">Export full comparison</button><button class="wide" id="copy-case">Explore these points live</button><p class="small">Use the included Python runner for new GNP predictions, then import its JSON in Surface explorer.</p>`;
 $('case').onchange=()=>{state.modelCase=Number($('case').value);updateModels()};$('model-display').onchange=()=>{state.modelDisplay=$('model-display').value;updateModels()};$('export-case').onclick=()=>download('gnp-comparison.json',JSON.stringify({schema:'jr-geometry-benchmark-v1',...cases[state.modelCase],provenance:window.GNP_BENCHMARKS?.provenance},null,2));$('copy-case').onclick=()=>{const c=cases[state.modelCase];storedImport={points:c.points,truth:c.truth,gnp:c.gnp,label:c.label,provenance:window.GNP_BENCHMARKS.provenance};state.shape='upload';state.display='reference';baseline=null;switchTab('geometry')};
 explain('Learning geometry from neighborhoods.',`<p>The authors’ pretrained GNP models estimate local surface representations from point-cloud neighborhoods. Differential geometry then turns those representations into quantities such as Gaussian curvature. Here, every color is tied to a recorded model output or an analytic reference.</p><details><summary>Read the comparison fairly</summary><p>Both methods receive the same coordinate samples. The GNP also receives exact clean-surface normal orientations in these controlled experiments; the local fit estimates its own frame from coordinates. These results are illustrative, not a broad or fully matched benchmark. Different normal estimates and sampling patterns may change the comparison.</p></details><details><summary>What is—and is not—demonstrated</summary><p>These examples test the 2.0.0 package’s pretrained curvature estimators. They do not reproduce the 2026 paper’s kernel-extension experiments or establish general reliability on unseen scans. The recorded Python runtime includes estimator setup and geometry estimation on this machine, not your device.</p></details><details><summary>Research source</summary><p>Methods and pretrained models by Blaine Quackenbush and Paul J. Atzberger. <a href="https://github.com/atzberg/geo_neural_op" target="_blank" rel="noopener">Read the implementation ↗</a>. See the Field guide for the three papers and reproducibility details.</p></details>`);
 } else if(t==='diffusion'){
 $('mode-title').textContent='Watch a field relax';
 $('control-body').innerHTML=range('radius','Sphere radius',.5,2,.1,state.radius)+range('diffusivity','Diffusivity D',.05,.6,.05,state.D)+range('time','Time',0,10,.1,state.time)+`<div class="button-row"><button id="play" class="primary">${playing?'Pause':'Play'}</button><button id="restart">Restart</button></div><p class="small">An exact heat-equation solution on a sphere. Values are normalized concentration, from 0 to 1.</p>`;
 $('radius').oninput=()=>{state.radius=Number($('radius').value);$('radius-value').textContent=state.radius;updateDiffusion()};$('diffusivity').oninput=()=>{state.D=Number($('diffusivity').value);$('diffusivity-value').textContent=state.D;updateDiffusion()};$('time').oninput=()=>{state.time=Number($('time').value);$('time-value').textContent=state.time;updateDiffusion()};$('play').onclick=()=>{playing=!playing;if(state.time>=10)state.time=0;$('play').textContent=playing?'Pause':'Play'};$('restart').onclick=()=>{state.time=0;playing=false;$('play').textContent='Play';$('time').value=0;$('time-value').textContent=0;updateDiffusion()};
 explain('The surface controls the timescale.',`<p>Start with more concentration in the northern hemisphere and less in the southern hemisphere. Diffusion spreads that difference across the surface. The color contrast fades toward a uniform value of 0.5 while the surface average stays constant.</p><details><summary>The exact solution</summary><p>u(y,t) = 0.5 + 0.5(y/r) exp(−2Dt/r²). It solves ∂u/∂t = D Δₛu on a sphere of radius r, where Δₛ is the surface Laplacian. There is no boundary on this closed surface. Time and diffusivity use consistent arbitrary units.</p></details><details><summary>Predict, then test</summary><p>Compare radii 1 and 2 at the same D and time. The decay timescale r²/(2D) becomes four times larger. Now double D. What happens to the timescale? This exact reference is useful for checking a numerical or learned operator.</p></details><details><summary>Connection to neural operators</summary><p>A neural solution operator could learn to map initial fields to later fields. This tab computes the stated formula directly. Its accuracy is not evidence of a trained model’s accuracy, and it represents this single initial-field family.</p></details>`);
 }else if(t==='topology'){
 $('mode-title').textContent='Gauss–Bonnet laboratory';
 $('control-body').innerHTML=field('gb-shape','Closed surface',select('gb-shape',[['sphere','Sphere · χ = 2'],['torus','Torus · χ = 0']],state.gbShape))+field('gb-density','Sample points',select('gb-density',[[600,'600'],[1200,'1,200'],[2200,'2,200']],state.gbN))+range('gb-noise','Coordinate noise σ',0,.03,.005,state.gbNoise)+field('gb-display','Curvature field',select('gb-display',[['reference','Analytic K'],['estimate','Local-fit K']],state.gbDisplay))+field('gb-neighbors','Neighborhood',select('gb-neighbors',[[20,'20 points'],[30,'30 points'],[50,'50 points']],state.gbK))+'<button id="gb-estimate" class="wide primary">Run local curvature fit</button><p class="small">Integrates K over a closed surface and compares the result with 2πχ. The local-fit case deliberately exposes discretization and noise error.</p>';
 $('gb-shape').onchange=()=>{state.gbShape=$('gb-shape').value;gbGeometry=null;state.gbDisplay='reference';updateTopology()};
 $('gb-density').onchange=()=>{state.gbN=Number($('gb-density').value);gbGeometry=null;state.gbDisplay='reference';updateTopology()};
 $('gb-noise').oninput=()=>{state.gbNoise=Number($('gb-noise').value);$('gb-noise-value').textContent=state.gbNoise;gbGeometry=null;state.gbDisplay='reference';updateTopology()};
 $('gb-neighbors').onchange=()=>{state.gbK=Number($('gb-neighbors').value);gbGeometry=null;if(state.gbDisplay==='estimate')state.gbDisplay='reference';updateTopology()};
 $('gb-display').onchange=()=>{state.gbDisplay=$('gb-display').value;if(state.gbDisplay==='estimate'&&!gbGeometry)runTopologyEstimate();else updateTopology()};
 $('gb-estimate').onclick=runTopologyEstimate;
 explain('Local bending adds up to a topological invariant.','<p>For a closed orientable surface, the Gauss–Bonnet theorem states ∫<sub>M</sub> K dA = 2πχ(M). A sphere has Euler characteristic χ = 2, so the integral is 4π. A torus has χ = 0, so positive and negative Gaussian curvature cancel globally.</p><details><summary>Why this is a serious validation test</summary><p>A curvature estimator can look smooth and still be globally wrong. Integrating the estimated field tests whether thousands of local measurements are collectively consistent with the topology. Increase noise or reduce the neighborhood and watch the inferred Euler characteristic drift.</p></details><details><summary>Quadrature used here</summary><p>The sphere uses equal-area Fibonacci samples. The torus uses parameter-space samples weighted by the analytic area element r(R + r cos v). For the estimated field, those clean-surface quadrature weights are retained intentionally so the experiment isolates curvature-estimation error.</p></details>');
 }else if(t==='spectrum'){
 $('mode-title').textContent='Hear the shape through its spectrum';
 $('control-body').innerHTML=range('spectrum-radius','Sphere radius',.5,2,.1,state.spectrumR)+field('spectrum-l','Mode degree ℓ',select('spectrum-l',[[0,'0 · constant'],[1,'1 · dipole'],[2,'2 · quadrupole'],[3,'3'],[4,'4'],[5,'5'],[6,'6']],state.spectrumL),true)+'<p class="small">Displays the axisymmetric spherical harmonic Pℓ(y/r). The eigenvalue is λℓ = ℓ(ℓ+1)/r² with multiplicity 2ℓ+1.</p>';
 $('spectrum-radius').oninput=()=>{state.spectrumR=Number($('spectrum-radius').value);$('spectrum-radius-value').textContent=state.spectrumR;updateSpectrum()};
 $('spectrum-l').onchange=()=>{state.spectrumL=Number($('spectrum-l').value);updateSpectrum()};
 explain('Geometry has a frequency spectrum.','<p>The Laplace–Beltrami operator is the intrinsic analogue of the ordinary Laplacian. On a sphere, spherical harmonics are its eigenfunctions: Δ<sub>S</sub>Y = −λY. Low-degree modes vary slowly across the surface; higher-degree modes oscillate more rapidly.</p><details><summary>What you are seeing</summary><p>This tab uses the exact zonal mode Pℓ(cos θ), not a numerical eigensolver. The full eigenspace for degree ℓ has multiplicity 2ℓ+1, so rotating or mixing basis functions produces different-looking modes with the same eigenvalue.</p></details><details><summary>Scale law</summary><p>Double the sphere radius and every eigenvalue falls by a factor of four. That same r⁻² scaling appears in Gaussian curvature and in diffusion timescales, linking geometry, PDEs, and spectral analysis.</p></details>');
 }else if(t==='flow'){
 $('mode-title').textContent='Evolve geometry by curvature';
 const extinction=state.flowR0*state.flowR0/4,maxTime=Math.max(.01,.99*extinction);state.flowTime=Math.min(state.flowTime,maxTime);
 $('control-body').innerHTML=range('flow-radius','Initial sphere radius',.6,2.2,.1,state.flowR0)+range('flow-time','Flow time',0,maxTime,Math.max(.002,maxTime/150),state.flowTime)+'<div class="button-row"><button id="flow-play" class="primary">'+(playing?'Pause':'Play')+'</button><button id="flow-restart">Restart</button></div><p class="small">Exact spherical mean-curvature flow reference: R(t)² = R₀² − 4t, up to the extinction time R₀²/4 under the stated convention.</p>';
 $('flow-radius').oninput=()=>{state.flowR0=Number($('flow-radius').value);$('flow-radius-value').textContent=state.flowR0;state.flowTime=0;const extinction=state.flowR0*state.flowR0/4,maxTime=Math.max(.01,.99*extinction);$('flow-time').max=maxTime;$('flow-time').step=Math.max(.002,maxTime/150);$('flow-time').value=0;$('flow-time-value').textContent='0';updateFlow()};
 $('flow-time').oninput=()=>{state.flowTime=Number($('flow-time').value);$('flow-time-value').textContent=fmt(state.flowTime,3);updateFlow()};
 $('flow-play').onclick=()=>{playing=!playing;$('flow-play').textContent=playing?'Pause':'Play'};
 $('flow-restart').onclick=()=>{playing=false;state.flowTime=0;controls();updateFlow()};
 explain('Curvature can move the surface itself.','<p>Mean-curvature flow moves a surface in its normal direction at a speed set by curvature. A perfect sphere remains a sphere while shrinking; its curvature rises as its radius falls, and the exact solution reaches a finite extinction time.</p><details><summary>Why include an exact flow?</summary><p>Exact solutions are valuable unit tests for numerical and learned geometric solvers. A future GNP or mesh-based flow can be compared against this trajectory rather than judged only by appearance.</p></details><details><summary>Connection to current GNP research</summary><p>The 2025 transferable-GNP work demonstrates pretrained geometric models as components for tasks including curvature-driven shape deformation. This browser tab is an analytic reference, not a claim that the network is running live.</p></details>');
 }else if(t==='inverse'){
 $('mode-title').textContent='Infer the hidden radius';
 $('control-body').innerHTML=range('true-radius','Simulated true radius',.6,2.2,.1,state.radius)+range('sigma','Measurement noise σ',.03,.3,.03,state.sigma)+range('count','Measurements',1,40,1,state.count)+`<button id="resample" class="wide primary">Take new measurements</button><p class="small">Infer radius from noisy Gaussian-curvature readings. The shaded band is the central 95% posterior credible interval.</p>`;
 for(const [id,key]of[['true-radius','radius'],['sigma','sigma'],['count','count']])$(id).oninput=()=>{state[key]=Number($(id).value);$(id+'-value').textContent=state[key];updateInverse()};$('resample').onclick=()=>{state.inverseSeed++;updateInverse()};
 explain('Work backward from evidence.',`<p>For a sphere, curvature and radius are linked by K = 1/r². Given noisy curvature measurements, Bayes’ rule combines their likelihood with a prior over possible radii. The posterior shows which radii are more plausible under those assumptions.</p><details><summary>Our model and assumptions</summary><p>Independent measurements: Kᵢ = 1/r² + εᵢ, with εᵢ normally distributed with known standard deviation σ. The prior is uniform on r ∈ [0.4, 2.5]. We normalize the likelihood on a 501-point radius grid. The true radius is available here because the experiment is simulated.</p></details><details><summary>What the interval means</summary><p>The displayed interval contains approximately 95% of the discrete posterior probability under this model. It is not a guarantee. Wrong noise assumptions, correlated readings, a non-spherical object, or an overly narrow prior can make it misleading.</p></details><details><summary>Try the trade-off</summary><p>Keep the radius fixed. Increase noise and watch the distribution widen. Add measurements and see how the uncertainty usually shrinks. This is a deliberately small Bayesian example; it does not reproduce the paper’s general manifold-shape inference.</p></details>`);
 }
}
function invalidate(){baseline=null;baselineGeometry=null;selectedIndex=null;job++;if(worker){worker.terminate();worker=null}state.display='reference';if($('display'))$('display').value='reference';if($('estimate')){$('estimate').disabled=false;$('estimate').textContent='Estimate curvature'}if($('point-inspector'))$('point-inspector').hidden=true}
function setView(points,vals,lo,hi){dataset.points=points;values=vals;const valid=vals.filter(Number.isFinite);lo=lo??Math.min(...valid);hi=hi??Math.max(...valid);if(!Number.isFinite(lo)){lo=0;hi=1}viewMin=lo;viewMax=hi;$('legend-min').textContent=fmt(lo,2);$('legend-max').textContent=fmt(hi,2);dirty=true}
let viewMin=0,viewMax=1;
function updateGeometry(){
 if(state.shape==='upload'&&storedImport){dataset={...storedImport,shape:'upload',noise:0};$('density').disabled=true;$('scale').disabled=true;$('noise').disabled=true;}
 else {dataset=G.generate(state.shape,state.n,state.scale,state.noise,state.seed);for(const id of ['density','scale','noise'])if($(id))$(id).disabled=false;}
 const truth=dataset.truth;const intros={sphere:['Every point bends the same way.','A sphere has equal positive Gaussian curvature everywhere. Its value depends on radius: make the sphere larger and its surface bends less sharply. The uniform reference color is a mathematical result, not a missing visualization.'],saddle:['Opposite bends, negative curvature.','A saddle bends upward in one principal direction and downward in the other. Multiplying these signed curvatures gives a negative value. Near the edge of this finite patch, one-sided sampling can make local estimates less accurate.'],upload:['Let the measurements speak.','Your points describe sampled geometry. A local fit estimates the shape of each neighborhood. Without an independently known reference, a smooth color map does not establish accuracy. Inspect boundaries, sparse regions, and noise before drawing conclusions.']};if(intros[state.shape]){$('explain-title').textContent=intros[state.shape][0];$('explain-body').querySelector('p').textContent=intros[state.shape][1];}else{$('explain-title').textContent='A donut has two kinds of bend.';$('explain-body').querySelector('p').textContent='On the outside of a torus, the surface bends the same way in both principal directions. On the inside, it bends in opposite directions, like a saddle. Gaussian curvature multiplies these two principal curvatures, so its sign distinguishes the two regions.';}
 let vals=truth,tag='Analytic reference',quantity='Gaussian curvature K · unit⁻²';
 if(state.display==='estimate'){vals=baselineGeometry?.gaussian;tag='Local quadratic fit';}
 else if(state.display==='mean'){vals=baselineGeometry?.meanAbs;tag='Local quadratic fit';quantity='Mean curvature magnitude |H| · unit⁻¹';}
 else if(state.display==='kmax'){vals=baselineGeometry?.kMaxAbs;tag='Local quadratic fit';quantity='Larger principal-curvature magnitude · unit⁻¹';}
 else if(state.display==='kmin'){vals=baselineGeometry?.kMinAbs;tag='Local quadratic fit';quantity='Smaller principal-curvature magnitude · unit⁻¹';}
 else if(state.display==='residual'){vals=baselineGeometry?.residual;tag='Quadratic-fit residual';quantity='Local RMS fit residual · units';}
 else if(state.display==='error'){vals=baselineGeometry?.gaussian?.map((v,i)=>truth?Math.abs(v-truth[i]):null);tag='Absolute K error';quantity='Absolute error |K estimate − K reference| · unit⁻²';}
 if(state.shape==='upload'&&state.display==='reference'){vals=storedImport.gnp||truth||dataset.points.map(()=>0);tag=storedImport.gnp?'Imported GNP prediction':truth?'Imported reference':'Imported geometry';}
 if(!vals)vals=dataset.points.map(()=>0);
 let reference=(state.display==='reference'||state.display==='estimate'||state.display==='error')?truth?.filter(Number.isFinite):null;
 let limits=reference?.length?[Math.min(...reference),Math.max(...reference)]:null;
 if(limits&&Math.abs(limits[1]-limits[0])<1e-10)limits=[0,Math.max(1,Math.abs(limits[1])*1.5)];
 if(['mean','kmax','kmin','residual','error'].includes(state.display))limits=[0,Math.max(...vals.filter(Number.isFinite),.01)];
 setView(dataset.points,vals,...(limits||[]));
 const viewQuantity={reference:'Gaussian curvature',estimate:'Gaussian curvature',mean:'|H|',kmax:'|κ|max',kmin:'|κ|min',residual:'fit residual',error:'K error'}[state.display]||'geometry';
 $('view-title').textContent=(state.shape==='upload'?'Your point cloud':titleCase(state.shape))+' / '+viewQuantity;$('method-badge').textContent=tag;$('legend-title').textContent=quantity;
 const st=baselineGeometry&&truth?G.stats(baselineGeometry.gaussian,truth):null;
 metrics([['Points',dataset.points.length.toLocaleString()],['K MAE',st?.mae!=null?fmt(st.mae):'—'],['K RMSE',st?.rmse!=null?fmt(st.rmse):'—'],['95% |K error|',st?.p95Ae!=null?fmt(st.p95Ae):'—']]);
 $('experiment-note').textContent=state.shape==='upload'?'Imported coordinates are displayed in their supplied units. Signed curvature depends on normal orientation, so this lab exposes orientation-invariant magnitudes for imported clouds unless a saved prediction supplies K.':baselineGeometry?'The same local quadratic patch supplies K, |H|, principal-curvature magnitudes, fit residual, and neighborhood scale. Error statistics compare K with the clean analytic surface at the original sample locations.':'Estimate local geometry to unlock second-order invariants and point-by-point diagnostics.';
 if($('display')){const opts=$('display').options;opts[6].disabled=!truth;opts[0].textContent=state.shape==='upload'?(storedImport.gnp?'Imported GNP prediction':'Imported geometry'):'Reference K'}
 updatePointInspector();
}
function runEstimate(){
 if(!dataset)return;const id=++job,points=dataset.points.map(p=>p.slice()),normals=dataset.normals?.map(n=>n.slice())||null;$('estimate').disabled=true;$('estimate').textContent='Computing…';status('Fitting local surface patches and deriving second-order invariants…');
 const done=r=>{if(r.id!==job)return;if(r.error){status('The fit could not be computed: '+r.error);$('estimate').disabled=false;$('estimate').textContent='Estimate curvature';return}baselineGeometry=r.geometry;baseline=r.geometry.gaussian;if(state.display==='reference')state.display='estimate';$('display').value=state.display;updateGeometry();$('estimate').disabled=false;$('estimate').textContent='Estimate curvature';status('Computed '+r.geometry.gaussian.length.toLocaleString()+' local differential-geometry fits in '+(r.ms/1000).toFixed(2)+' seconds on this device.')};
 try{worker=new Worker('worker.js?v=20260924-research-v2');worker.onmessage=e=>{done(e.data);worker.terminate();worker=null};worker.onerror=()=>{worker.terminate();worker=null;const t=performance.now();try{done({id,geometry:G.estimateGeometry(points,state.k,normals),ms:performance.now()-t})}catch(e){done({id,error:e.message})}};worker.postMessage({id,points,k:state.k,normals})}catch(e){setTimeout(()=>{const t=performance.now();done({id,geometry:G.estimateGeometry(points,state.k,normals),ms:performance.now()-t})},20)}
}
function updateModels(){
 const c=window.GNP_BENCHMARKS?.cases?.[state.modelCase];if(!c){status('The benchmark data file did not load. Check that benchmarks.js was copied with the lab.');return}dataset={...c};
 let vals=state.modelDisplay==='reference'?c.truth:state.modelDisplay==='baseline'?c.baseline:state.modelDisplay==='error'?c.gnp.map((v,i)=>Math.abs(v-c.truth[i])):c.gnp;
 let lo=Math.min(...c.truth),hi=Math.max(...c.truth);if(hi-lo<1e-8){lo=0;hi=Math.max(1,hi*1.5)}if(state.modelDisplay==='error'){lo=0;hi=Math.max(...vals)}setView(c.points,vals,lo,hi);
 $('view-title').textContent=c.label;$('method-badge').textContent=state.modelDisplay==='reference'?'Analytic reference':state.modelDisplay==='baseline'?'Recorded local fit':state.modelDisplay==='error'?'Recorded GNP error':'Recorded GNP prediction';$('legend-title').textContent=state.modelDisplay==='error'?'Absolute curvature error · unit⁻²':'Gaussian curvature K · unit⁻²';
 const gs=G.stats(c.gnp,c.truth),ls=G.stats(c.baseline,c.truth);metrics([['GNP K MAE',fmt(gs.mae)],['GNP K RMSE',fmt(gs.rmse)],['GNP 95% |error|',fmt(gs.p95Ae)],['Local fit K MAE',fmt(ls.mae)],['GNP bias',fmt(gs.bias)],['GNP runtime · recorded',fmt(c.seconds,2)+' s']]);
 $('experiment-note').textContent=`${c.points.length.toLocaleString()} identical input points · ${c.model} · σ = ${c.noise} coordinate units · seed ${c.seed}. Exact normal orientations supplied to GNP. Colors share the analytic range (outliers saturate).`;
}
function updateDiffusion(){dataset=G.generate('sphere',1200,state.radius);setView(dataset.points,G.diffusion(dataset.points,state.radius,state.time,state.D),0,1);$('view-title').textContent='Sphere / diffusion';$('method-badge').textContent='Exact heat-equation solution';$('legend-title').textContent='Normalized concentration · 0 to 1';metrics([['Elapsed time',fmt(state.time,1)],['Surface average','0.500'],['Decay timescale r² / 2D',fmt(state.radius**2/(2*state.D),2)]]);$('experiment-note').textContent='A larger sphere relaxes more slowly at the same diffusivity. The average is exactly 0.5 for this initial field; changing the radius or diffusivity recomputes the same solution family.'}
function updateTopology(){
 gbDataset=G.generate(state.gbShape,state.gbN,1,state.gbNoise,42);dataset=gbDataset;
 let vals=state.gbDisplay==='estimate'?gbGeometry?.gaussian:gbDataset.truth;if(!vals)vals=gbDataset.truth;
 let lo=Math.min(...gbDataset.truth),hi=Math.max(...gbDataset.truth);if(Math.abs(hi-lo)<1e-10){lo=0;hi=Math.max(1,hi*1.5)}
 setView(gbDataset.points,vals,lo,hi);
 const gb=G.gaussBonnet(gbDataset,vals),expected=gb.expectedIntegral,error=expected==null||gb.integral==null?null:Math.abs(gb.integral-expected);
 $('view-title').textContent=titleCase(state.gbShape)+' / Gauss–Bonnet curvature integral';$('method-badge').textContent=state.gbDisplay==='estimate'?'Local quadratic curvature':'Analytic curvature';$('legend-title').textContent='Gaussian curvature K · unit⁻²';
 metrics([['∫ K dA',gb.integral==null?'—':fmt(gb.integral,4)],['Expected 2πχ',expected==null?'—':fmt(expected,4)],['Inferred χ',gb.chi==null?'—':fmt(gb.chi,4)],['Integral error',error==null?'—':fmt(error,4)]]);
 $('experiment-note').textContent=state.gbDisplay==='estimate'?'The local estimator is integrated with clean-surface area weights. Noise and finite neighborhoods can make the inferred Euler characteristic depart from its integer topological value.':'The analytic reference with its matching quadrature should approach the topological target; the sphere case is exact up to floating-point arithmetic for constant K.';
 updatePointInspector();
}
function runTopologyEstimate(){
 if(!gbDataset)updateTopology();const id=++job,points=gbDataset.points.map(p=>p.slice()),normals=gbDataset.normals?.map(n=>n.slice())||null;const b=$('gb-estimate');if(b){b.disabled=true;b.textContent='Computing…'}status('Estimating local curvature before the global topology test…');
 const done=r=>{if(r.id!==job)return;if(r.error){status('The topology fit could not be computed: '+r.error);if(b){b.disabled=false;b.textContent='Run local curvature fit'}return}gbGeometry=r.geometry;state.gbDisplay='estimate';if($('gb-display'))$('gb-display').value='estimate';updateTopology();if(b){b.disabled=false;b.textContent='Run local curvature fit'}status('Integrated '+r.geometry.gaussian.length.toLocaleString()+' local curvature estimates in '+(r.ms/1000).toFixed(2)+' seconds.')};
 try{worker=new Worker('worker.js?v=20260924-research-v2');worker.onmessage=e=>{done(e.data);worker.terminate();worker=null};worker.onerror=()=>{worker.terminate();worker=null;const t=performance.now();try{done({id,geometry:G.estimateGeometry(points,state.gbK,normals),ms:performance.now()-t})}catch(e){done({id,error:e.message})}};worker.postMessage({id,points,k:state.gbK,normals})}catch(e){setTimeout(()=>{const t=performance.now();done({id,geometry:G.estimateGeometry(points,state.gbK,normals),ms:performance.now()-t})},20)}
}
function updateSpectrum(){
 dataset=G.generate('sphere',1400,state.spectrumR,0,42);const mode=G.spectralSphere(dataset.points,state.spectrumR,state.spectrumL);setView(dataset.points,mode.values,-1,1);
 const area=dataset.areaWeights.reduce((a,b)=>a+b,0),weightedMean=G.integrate(mode.values,dataset.areaWeights)/area;
 $('view-title').textContent='Sphere / Laplace–Beltrami mode ℓ = '+state.spectrumL;$('method-badge').textContent='Exact spherical-harmonic reference';$('legend-title').textContent='Zonal eigenfunction amplitude';
 metrics([['Eigenvalue λℓ',fmt(mode.eigenvalue,4)],['Multiplicity',String(mode.multiplicity)],['Weighted mean',fmt(weightedMean,5)],['Radius scaling','λ ∝ r⁻²']]);
 $('experiment-note').textContent=state.spectrumL===0?'The constant mode has eigenvalue zero. It represents the null space of the Laplace–Beltrami operator on a connected closed surface.':'For every ℓ > 0, the exact surface average is zero. Small nonzero displayed means come from finite sampling quadrature.';
 updatePointInspector();
}
function updateFlow(){
 const flow=G.meanCurvatureFlowSphere(state.flowR0,state.flowTime),r=Math.max(flow.radius,.03);dataset=G.generate('sphere',1200,r,0,42);setView(dataset.points,dataset.truth,0,Math.max(1,flow.gaussian));
 $('view-title').textContent='Sphere / mean-curvature flow';$('method-badge').textContent='Exact shrinking-sphere reference';$('legend-title').textContent='Gaussian curvature K · unit⁻²';
 metrics([['Current radius',fmt(flow.radius,4)],['Extinction time',fmt(flow.extinction,4)],['Gaussian curvature',Number.isFinite(flow.gaussian)?fmt(flow.gaussian,4):'∞'],['Surface area',fmt(flow.area,4)]]);
 $('experiment-note').textContent='As the radius shrinks, curvature rises. The visualization remains a sphere because symmetry is preserved exactly for this reference solution.';
 updatePointInspector();
}
function updateInverse(){posterior=G.posterior(state.radius,state.sigma,state.count,state.inverseSeed);dataset=G.generate('sphere',1200,posterior.mean);setView(dataset.points,dataset.points.map(()=>1/posterior.mean**2),0,4);$('view-title').textContent='Reconstructed sphere / posterior mean radius';$('method-badge').textContent='Bayesian grid calculation';$('legend-title').textContent='Inferred Gaussian curvature · unit⁻²';metrics([['Posterior mean radius',fmt(posterior.mean)],['95% credible interval',fmt(posterior.lo,2)+'–'+fmt(posterior.hi,2)],['Simulated true radius',fmt(state.radius,2)]]);$('experiment-note').textContent='The 3D surface shows the posterior mean radius. The distribution below shows uncertainty; the dashed line marks the simulated true radius.';drawPosterior()}
function drawPosterior(){if(!posterior)return;const svg=$('posterior-chart'),w=Math.max(280,svg.clientWidth),h=200,l=48,r=16,top=18,bottom=38,mx=Math.max(...posterior.ys);const x=v=>l+(v-.4)/2.1*(w-l-r),y=v=>h-bottom-v/mx*(h-top-bottom),points=posterior.xs.map((v,i)=>`${x(v)},${y(posterior.ys[i])}`).join(' ');svg.setAttribute('viewBox',`0 0 ${w} ${h}`);svg.innerHTML=`<rect x="${x(posterior.lo)}" y="${top}" width="${x(posterior.hi)-x(posterior.lo)}" height="${h-top-bottom}" fill="var(--accent)" opacity=".12"/><line x1="${l}" y1="${h-bottom}" x2="${w-r}" y2="${h-bottom}" stroke="var(--line)"/><polyline points="${points}" fill="none" stroke="var(--accent)" stroke-width="2"/><line x1="${x(state.radius)}" x2="${x(state.radius)}" y1="${top}" y2="${h-bottom}" stroke="var(--cyan)" stroke-dasharray="4 4"/>`+[.5,1,1.5,2,2.5].map(v=>`<text x="${x(v)}" y="${h-20}" fill="var(--muted)" font-size="12" text-anchor="middle">${v}</text>`).join('')+`<text x="${w/2}" y="${h-2}" fill="var(--muted)" font-size="12" text-anchor="middle">Radius · units</text><text x="${l}" y="12" fill="var(--muted)" font-size="11">Posterior probability · peak scaled to 1</text>`}
async function importCloud(e){
 const f=e.target.files[0];if(!f)return;if(f.size>2*1024*1024){status('Choose a file smaller than 2 MB.');return}
 try{const text=await f.text();let points=[],pred=null,truth=null,provenance=null;if(f.name.toLowerCase().endsWith('.json')){let j=JSON.parse(text);points=Array.isArray(j)?j:j.points;pred=j.gnp||null;truth=j.truth||null;provenance=j.provenance||null;if(!Array.isArray(points))throw Error('JSON needs a points array.')}else{let obj=f.name.toLowerCase().endsWith('.obj');for(const line of text.split(/\r?\n/)){let s=line.trim();if(!s||s.startsWith('#'))continue;if(obj){if(!/^v\s/.test(s))continue;s=s.replace(/^v\s+/,'')}let p=s.split(/[\s,;]+/).slice(0,3).map(Number);if(p.length===3&&p.every(Number.isFinite))points.push(p);else if(!/^[xyzXYZ,;\s]+$/.test(s))throw Error('Each data row needs three finite coordinates.')}}
 if(points.length<30)throw Error('Provide at least 30 points.');if(!points.every(p=>Array.isArray(p)&&p.length===3&&p.every(v=>typeof v==='number'&&Number.isFinite(v)&&Math.abs(v)<1e8)))throw Error('Coordinates must be finite numbers with magnitude below 100 million.');for(const a of[pred,truth])if(a&&(!Array.isArray(a)||a.length!==points.length||!a.every(Number.isFinite)))throw Error('Curvature arrays must match the point count and contain finite numbers.');
 if(Math.max(...[0,1,2].map(a=>Math.max(...points.map(p=>p[a]))-Math.min(...points.map(p=>p[a]))))<1e-10)throw Error('The point cloud needs nonzero spatial extent.');const n=points.length,inds=Array.from({length:Math.min(n,2200)},(_,i)=>Math.floor(i*n/Math.min(n,2200)));storedImport={points:inds.map(i=>points[i]),gnp:pred?inds.map(i=>pred[i]):null,truth:truth?inds.map(i=>truth[i]):null,provenance,label:f.name};invalidate();state.shape='upload';controls();updateGeometry();status(`Loaded ${Math.min(n,2200).toLocaleString()} of ${n.toLocaleString()} points from ${f.name}.`);
 }catch(err){status('Could not import: '+err.message)}
}
function snapshot(){return {schema:'jr-geometry-experiment-v1',version:'1.0.0',created:new Date().toISOString(),state:{...state},points:dataset?.points,values,truth:dataset?.truth||null,baseline,provenance:state.tab==='models'?window.GNP_BENCHMARKS.provenance:state.shape==='upload'?storedImport?.provenance:null,method:$('method-badge').textContent,posterior:state.tab==='inverse'?posterior:null}}
function download(name,data,type='application/json'){const a=document.createElement('a'),u=URL.createObjectURL(new Blob([data],{type}));a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),3000)}
function readNotes(){try{const n=JSON.parse(localStorage.getItem('jr-geometry-notebook-v1')||'[]');return Array.isArray(n)?n:[]}catch{return[]}}
function showNotebook(){const notes=readNotes();$('notebook-panel').innerHTML=`<p class="eyebrow">YOUR EXPERIMENTS / THIS DEVICE</p><h2>Keep the question with the result.</h2><p>Record predictions, compare outcomes, and choose the next experiment. Browser storage can be cleared; export important records.</p><div class="button-row"><button id="export-notebook">Export notebook</button></div><div id="notes-list"></div>`;if(!notes.length)$('notes-list').innerHTML='<div class="note-card"><h3>No experiments saved yet.</h3><p>Open an experiment, change a parameter, and select Save experiment.</p><button id="back-explore">Open surface explorer</button></div>';else $('notes-list').innerHTML=notes.map((n,i)=>`<article class="note-card"><p class="eyebrow">${escapeHtml(labels[n.state.tab]||n.state.tab)} / ${escapeHtml(new Date(n.created).toLocaleDateString())}</p><h3>${escapeHtml(n.name)}</h3><p>${escapeHtml(n.notes||'No observations recorded.')}</p><small>${escapeHtml(n.method)} · ${n.points?.length||0} points</small><div class="button-row"><button data-restore="${i}">Restore experiment</button><button data-export="${i}">Export JSON</button><button data-delete="${i}">Delete</button></div></article>`).join('');$('export-notebook').onclick=()=>download('geometry-notebook.json',JSON.stringify({schema:'jr-geometry-notebook-v1',experiments:notes},null,2));if($('back-explore'))$('back-explore').onclick=()=>switchTab('geometry');document.querySelectorAll('[data-export]').forEach(b=>b.onclick=()=>download('geometry-experiment.json',JSON.stringify(notes[+b.dataset.export],null,2)));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{if(!confirm('Delete this saved experiment from this device?'))return;notes.splice(+b.dataset.delete,1);try{localStorage.setItem('jr-geometry-notebook-v1',JSON.stringify(notes));showNotebook()}catch{status('Browser storage is unavailable.')}});document.querySelectorAll('[data-restore]').forEach(b=>b.onclick=()=>{const n=notes[+b.dataset.restore];invalidate();Object.assign(state,n.state);if(state.shape==='upload')storedImport={points:n.points,truth:n.truth,gnp:n.method==='Imported GNP prediction'?n.values:null,provenance:n.provenance};baseline=n.baseline;switchTab(state.tab);status('Restored experiment settings and saved data. Camera position is reset separately.')})}
function showGuide(){
 $('learn-panel').innerHTML=`<p class="eyebrow">FIELD GUIDE / FROM INTUITION TO RESEARCH</p><h2>Seven experiments. One scientific habit.</h2><p>Predict a result, change one variable, measure the difference, and explain what you learned.</p><div class="guide-grid">
 <article class="guide-card"><p class="eyebrow">01 / GEOMETRY</p><h2>A surface has its own distances.</h2><p>An ant walks along a sphere, not straight through it. A metric tells us how to measure lengths and angles on the surface. Curvature describes how the surface bends. Gaussian curvature multiplies the two principal curvatures: positive on a sphere, negative on a saddle, and zero on the side of an ideal cylinder.</p><p class="formula">Sphere: K = 1/r²</p><p>Try sizes 0.6 and 1.2. The sphere doubles in radius, but its Gaussian curvature falls to one quarter.</p><button data-go="geometry">Explore curvature ↗</button></article>
 <article class="guide-card"><p class="eyebrow">02 / LEARNING</p><h2>An operator acts on a field.</h2><p>A field assigns a value to every location, like temperature across a surface. An operator transforms one field into another. A neural operator learns a transformation from examples while incorporating spatial relationships. These GNPs learn local surface representations that support geometric calculations.</p><p>Inspect predictions and errors separately. A visually smooth result is not evidence that a calculation is correct. Reference data and carefully chosen tests matter.</p><button data-go="models">Compare recorded predictions ↗</button></article>
 <article class="guide-card"><p class="eyebrow">03 / PHYSICS</p><h2>Geometry changes diffusion.</h2><p>The surface Laplacian describes local spreading along a surface. In the sphere experiment, the north–south concentration difference decays exponentially. A larger sphere has a longer distance over which to relax.</p><p class="formula">Timescale τ = r²/(2D)</p><p>Doubling radius multiplies this timescale by four. Doubling diffusivity divides it by two. This exact solution is a reference case for testing approximate solvers.</p><button data-go="diffusion">Run diffusion ↗</button></article>
 <article class="guide-card"><p class="eyebrow">04 / INFERENCE</p><h2>Observations constrain a shape.</h2><p>A forward model predicts measurements from a shape. An inverse model asks which shapes could explain measurements. Bayesian inference combines a prior and a likelihood into a posterior distribution.</p><p class="formula">Posterior ∝ likelihood × prior</p><p>Our sphere example assumes independent Gaussian noise and a bounded uniform radius prior. A narrow interval can still be wrong if the assumptions are wrong.</p><button data-go="inverse">Infer a radius ↗</button></article>
 <article class="guide-card"><p class="eyebrow">05 / TOPOLOGY</p><h2>Local curvature knows global topology.</h2><p>Gauss–Bonnet links a continuous geometric field to the discrete Euler characteristic.</p><p class="formula">∫M K dA = 2πχ(M)</p><p>A sphere integrates to 4π; a torus integrates to zero because positive and negative curvature cancel.</p><button data-go="topology">Test Gauss–Bonnet ↗</button></article>
 <article class="guide-card"><p class="eyebrow">06 / SPECTRAL GEOMETRY</p><h2>A shape has intrinsic frequencies.</h2><p>Laplace–Beltrami eigenfunctions form natural modes on a surface. On a sphere, degree ℓ has eigenvalue ℓ(ℓ+1)/r² and multiplicity 2ℓ+1.</p><p class="formula">ΔS Y = −λY</p><p>Changing radius changes the spectrum without changing topology.</p><button data-go="spectrum">Explore the spectrum ↗</button></article>
 <article class="guide-card"><p class="eyebrow">07 / GEOMETRIC FLOW</p><h2>Curvature can evolve the shape.</h2><p>Under mean-curvature flow a perfect sphere stays spherical while shrinking, providing an exact validation trajectory for numerical or learned solvers.</p><p class="formula">R(t)² = R₀² − 4t</p><button data-go="flow">Run curvature flow ↗</button></article>
 <article class="guide-card wide"><p class="eyebrow">CREDITS / COMPLETED CONTRIBUTIONS</p><h2>Website adaptation and enhancements by Joshua Randall.</h2><p>Joshua Randall developed the interactive website adaptation, responsive interface, live numerical experiments, model-comparison presentation, experiment notebook, import/export features, supporting Python workflow, and guided learning material.</p><p>The original GNP research, upstream software, and pretrained models are credited to Blaine Quackenbush and Paul J. Atzberger, with repository contributions credited upstream. The recorded neural predictions were generated using their models.</p><p>These additions extend the application and learning experience. Established mathematical methods retain their scientific attribution; no new GNP architecture or improvement to the pretrained models is claimed.</p><p><a href="CREDITS.md">Full credits and contribution record ↗</a></p></article>
 <article class="guide-card wide"><p class="eyebrow">RESEARCH / PRIMARY SOURCES</p><h2>Built around a reproducible comparison.</h2><ol><li><a href="https://doi.org/10.1007/s10462-024-11051-3" target="_blank" rel="noopener">Vijendran et al. (2025): AI for Geometry-Based Feature Extraction, Analysis and Synthesis in Artistic Images</a> · <a href="https://arxiv.org/abs/2412.01450" target="_blank" rel="noopener">Open manuscript</a>. Broad survey context for explicit geometric representations in extraction, analysis, and synthesis.</li><li><a href="https://doi.org/10.1088/2632-2153/ad8980" target="_blank" rel="noopener">Quackenbush & Atzberger (2024): Geometric Neural Operators</a> · <a href="https://arxiv.org/abs/2404.10843" target="_blank" rel="noopener">Open manuscript</a>. Geometric features, PDEs on manifolds, and shape inference.</li><li><a href="https://doi.org/10.1088/2632-2153/ae1bf8" target="_blank" rel="noopener">Transferable Foundation Models for Geometric Tasks (2025)</a> · <a href="https://arxiv.org/abs/2503.04649" target="_blank" rel="noopener">Open manuscript</a>. Reusable pretrained models and robustness experiments.</li><li><a href="https://arxiv.org/abs/2603.03621" target="_blank" rel="noopener">Extending Neural Operators (March 2026 preprint)</a>. Kernel extensions and derivative-aware approximation under stated mathematical conditions. This lab does not reproduce those extension results.</li><li><a href="https://github.com/atzberg/geo_neural_op" target="_blank" rel="noopener">geo_neural_op source and weights</a> · GPL-3.0. The benchmark export records the exact upstream revision and weight hashes.</li></ol><p>The artistic-image survey motivates the broader value of explicit geometric structure but is not implemented as an image-analysis model here. The browser baseline, analytic diffusion, Gauss–Bonnet quadrature, spherical spectral modes, exact mean-curvature flow, and Bayesian sphere calculation are separate educational implementations. They are not replicas of all methods in the papers. Imported scans require suitable sampling, units, and validation.</p><p><a href="METHODS.md">Read complete methods and limitations</a></p></article>
 <article class="guide-card wide"><p class="eyebrow">NEXT / A PERSONAL RESEARCH PROJECT</p><h2>How much noise is too much?</h2><p>Hold shape, point count, and seed fixed. Vary coordinate noise and neighborhood size. Save each result, compare mean absolute error, and repeat with several seeds. For a stronger study, vary sampling density and normal quality independently. Report failures as well as successes.</p><p>For new neural predictions, use the included research runner with the authors’ package, then import its JSON. Your uploaded data stays local unless you independently choose to send it elsewhere.</p></article></div>`;document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>switchTab(b.dataset.go))
}
function updatePointInspector(){
 const el=$('point-inspector');if(!el)return;
 if(selectedIndex==null||!dataset?.points?.[selectedIndex]){el.hidden=true;return}
 const i=selectedIndex,p=dataset.points[i],rows=[['Sample','#'+(i+1)],['x, y, z',p.map(v=>fmt(v,4)).join(', ')]];
 if(state.tab==='geometry'){
  if(Number.isFinite(dataset.truth?.[i]))rows.push(['Reference K',fmt(dataset.truth[i],5)]);
  if(baselineGeometry){
   rows.push(['Estimated K',fmt(baselineGeometry.gaussian[i],5)],['|H|',fmt(baselineGeometry.meanAbs[i],5)],['|κ|max / |κ|min',fmt(baselineGeometry.kMaxAbs[i],5)+' / '+fmt(baselineGeometry.kMinAbs[i],5)],['Fit RMS',fmt(baselineGeometry.residual[i],6)],['Neighborhood radius',fmt(baselineGeometry.radius[i],5)]);
  }
 }else if(state.tab==='models'){
  const b=window.GNP_BENCHMARKS?.cases?.[state.modelCase];if(b){rows.push(['Reference K',fmt(b.truth[i],5)],['GNP K',fmt(b.gnp[i],5)],['Local-fit K',fmt(b.baseline[i],5)],['GNP |error|',fmt(Math.abs(b.gnp[i]-b.truth[i]),5)])}
 }else if(state.tab==='topology'){
  if(Number.isFinite(gbDataset?.truth?.[i]))rows.push(['Reference K',fmt(gbDataset.truth[i],5)]);
  if(gbGeometry)rows.push(['Estimated K',fmt(gbGeometry.gaussian[i],5)],['Local |H|',fmt(gbGeometry.meanAbs[i],5)],['Fit RMS',fmt(gbGeometry.residual[i],6)]);
 }else if(state.tab==='spectrum'){
  rows.push(['Mode amplitude',fmt(values[i],5)],['Degree ℓ',String(state.spectrumL)]);
 }else if(state.tab==='flow'){
  rows.push(['Gaussian K',fmt(values[i],5)],['Flow time',fmt(state.flowTime,4)]);
 }else if(state.tab==='diffusion'){
  rows.push(['Concentration',fmt(values[i],5)],['Time',fmt(state.time,3)]);
 }
 el.innerHTML='<div class="inspector-head"><strong>Point inspector</strong><span>tap another sample to compare</span></div><div class="inspector-grid">'+rows.map(r=>'<div><span>'+escapeHtml(r[0])+'</span><strong>'+escapeHtml(r[1])+'</strong></div>').join('')+'</div>';
 el.hidden=false;
}
function switchTab(t){if(!['geometry','models','diffusion','topology','spectrum','flow','inverse','notebook','learn'].includes(t))t='geometry';if(worker){worker.terminate();worker=null;job++}playing=false;selectedIndex=null;state.tab=t;if(t==='diffusion')state.radius=Math.max(.5,Math.min(2,state.radius));if(t==='inverse')state.radius=Math.max(.6,Math.min(2.2,state.radius));document.querySelectorAll('[data-tab]').forEach(b=>{if(b.dataset.tab===t)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});const exp=!['notebook','learn'].includes(t);$('experiment').hidden=!exp;$('explanation').hidden=!exp;$('learn-panel').hidden=t!=='learn';$('notebook-panel').hidden=t!=='notebook';$('save-experiment').hidden=!exp;$('chart-wrap').hidden=t!=='inverse';if($('point-inspector'))$('point-inspector').hidden=true;status('');history.replaceState(null,'','#'+t);if(t==='learn')showGuide();else if(t==='notebook')showNotebook();else{controls();if(t==='geometry')updateGeometry();if(t==='models')updateModels();if(t==='diffusion')updateDiffusion();if(t==='topology')updateTopology();if(t==='spectrum')updateSpectrum();if(t==='flow')updateFlow();if(t==='inverse')updateInverse()}dirty=true}
// Canvas projection uses original coordinates and a view-only normalization.
const canvas=$('scene'),ctx=canvas.getContext('2d');let width=600,height=420;
function color(v){if(!Number.isFinite(v))return '#8b9092';const t=Math.max(0,Math.min(1,(v-viewMin)/(viewMax-viewMin||1)));let a=[39,140,161],b=[242,187,101];return `rgb(${a.map((x,i)=>Math.round(x+(b[i]-x)*t)).join(',')})`}
function draw(){if(!dataset||!ctx)return;const dpr=Math.min(window.devicePixelRatio||1,2);const rect=canvas.getBoundingClientRect();if(rect.width===0)return;if(width!==rect.width||height!==rect.height||canvas.width!==Math.round(rect.width*dpr)){width=rect.width;height=rect.height;canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr)}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,width,height);const css=getComputedStyle(document.documentElement),line=css.getPropertyValue('--line').trim();ctx.strokeStyle=line;ctx.lineWidth=.5;ctx.globalAlpha=.28;for(let x=width/2%35;x<width;x+=35){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,height);ctx.stroke()}for(let y=height/2%35;y<height;y+=35){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(width,y);ctx.stroke()}ctx.globalAlpha=1;
 const p=dataset.points,mins=[0,1,2].map(a=>Math.min(...p.map(q=>q[a]))),maxs=[0,1,2].map(a=>Math.max(...p.map(q=>q[a]))),center=mins.map((v,i)=>(v+maxs[i])/2),extent=Math.max(...maxs.map((v,i)=>(v-mins[i])/2))||1,scale=Math.min(width*.40,height*.43)*zoom/extent,c=Math.cos(angleY),s=Math.sin(angleY),cx=Math.cos(angleX),sx=Math.sin(angleX);
 const projected=p.map((q,i)=>{let [x,y,z]=q.map((v,a)=>v-center[a]),xx=x*c+z*s,zz=-x*s+z*c,yy=y*cx-zz*sx,depth=y*sx+zz*cx;return{x:width/2+xx*scale,y:height/2-yy*scale,z:depth,i}}).sort((a,b)=>a.z-b.z);projectedCache=projected;
 for(const q of projected){let f=(q.z/extent+1)/2;ctx.globalAlpha=.22+.78*Math.max(0,Math.min(1,f));ctx.fillStyle=color(values[q.i]);ctx.beginPath();ctx.arc(q.x,q.y,Math.max(1.1,Math.min(3.4,(width<500?2:2.7)*zoom)),0,2*Math.PI);ctx.fill()}ctx.globalAlpha=1;
 if(selectedIndex!=null){const q=projected.find(p=>p.i===selectedIndex);if(q){ctx.strokeStyle=css.getPropertyValue('--accent').trim();ctx.lineWidth=2.5;ctx.beginPath();ctx.arc(q.x,q.y,8,0,2*Math.PI);ctx.stroke();ctx.fillStyle=css.getPropertyValue('--text').trim();ctx.beginPath();ctx.arc(q.x,q.y,2.2,0,2*Math.PI);ctx.fill()}}
 ctx.font='11px system-ui';ctx.fillStyle=css.getPropertyValue('--muted').trim();ctx.fillText('Y',28,height-67);ctx.fillText('X',55,height-35);ctx.strokeStyle=line;ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(30,height-40);ctx.lineTo(30,height-62);ctx.moveTo(30,height-40);ctx.lineTo(51,height-40);ctx.stroke();
}
function selectPointAt(e){const r=canvas.getBoundingClientRect(),sx=canvas.width/Math.max(1,r.width),sy=canvas.height/Math.max(1,r.height),x=(e.clientX-r.left)*sx,y=(e.clientY-r.top)*sy;let best=null,bestD=Infinity;for(let j=projectedCache.length-1;j>=0;j--){const q=projectedCache[j],d=(q.x-x)**2+(q.y-y)**2;if(d<bestD){bestD=d;best=q}}selectedIndex=best?.i??null;updatePointInspector();dirty=true}
let pointer=null;canvas.onpointerdown=e=>{pointer={x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,moved:false,id:e.pointerId};try{canvas.setPointerCapture(e.pointerId)}catch{}};canvas.onpointermove=e=>{if(!pointer)return;const dx=e.clientX-pointer.x,dy=e.clientY-pointer.y;if(Math.hypot(e.clientX-pointer.startX,e.clientY-pointer.startY)>5)pointer.moved=true;angleY+=dx*.008;angleX+=dy*.008;pointer.x=e.clientX;pointer.y=e.clientY;dirty=true};canvas.onpointerup=e=>{if(pointer&&!pointer.moved)selectPointAt(e);pointer=null};canvas.onpointercancel=()=>pointer=null;canvas.onwheel=e=>{e.preventDefault();zoom=Math.max(.35,Math.min(2.5,zoom*Math.exp(-e.deltaY*.001)));dirty=true};canvas.onkeydown=e=>{let used=true;if(e.key==='ArrowLeft')angleY-=.12;else if(e.key==='ArrowRight')angleY+=.12;else if(e.key==='ArrowUp')angleX-=.12;else if(e.key==='ArrowDown')angleX+=.12;else if(e.key==='+'||e.key==='=')zoom=Math.min(2.5,zoom*1.1);else if(e.key==='-')zoom=Math.max(.35,zoom/1.1);else used=false;if(used){e.preventDefault();dirty=true}};
$('zoom-in').onclick=()=>{zoom=Math.min(2.5,zoom*1.15);dirty=true};$('zoom-out').onclick=()=>{zoom=Math.max(.35,zoom/1.15);dirty=true};$('reset-view').onclick=()=>{angleY=.5;angleX=-.35;zoom=1;dirty=true};$('spin').onclick=()=>{spinning=!spinning;$('spin').setAttribute('aria-pressed',String(spinning));$('spin').textContent=spinning?'Stop':'Rotate'};
function tick(now){const dt=Math.min(.05,(now-lastTime)/1000||0);lastTime=now;if(!document.hidden&&!$('experiment').hidden){if(spinning){angleY+=dt*.25;dirty=true}if(playing&&state.tab==='diffusion'){state.time=Math.min(10,state.time+dt);if(state.time>=10){playing=false;if($('play'))$('play').textContent='Play'}if($('time'))$('time').value=state.time;if($('time-value'))$('time-value').textContent=fmt(state.time,1);updateDiffusion()}if(playing&&state.tab==='flow'){const extinction=state.flowR0*state.flowR0/4,maxTime=.99*extinction;state.flowTime=Math.min(maxTime,state.flowTime+dt*maxTime/6);if(state.flowTime>=maxTime){playing=false;if($('flow-play'))$('flow-play').textContent='Play'}if($('flow-time'))$('flow-time').value=state.flowTime;if($('flow-time-value'))$('flow-time-value').textContent=fmt(state.flowTime,3);updateFlow()}if(dirty){draw();dirty=false}}requestAnimationFrame(tick)}requestAnimationFrame(tick);new ResizeObserver(()=>{dirty=true;if(state.tab==='inverse')drawPosterior()}).observe($('stage'));
if(window.PortfolioTheme){document.addEventListener('portfolio:theme',()=>{dirty=true});}
else{
try{document.documentElement.dataset.theme=localStorage.getItem('jr-geometry-theme')||'dark'}catch{}
function themeLabel(){$('theme').textContent=document.documentElement.dataset.theme==='dark'?'Light mode':'Dark mode';$('theme').setAttribute('aria-label','Switch to '+(document.documentElement.dataset.theme==='dark'?'light':'dark')+' theme')}
$('theme').onclick=()=>{const next=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=next;try{localStorage.setItem('jr-geometry-theme',next)}catch{}themeLabel();dirty=true};themeLabel();
}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));$('sources-link').onclick=e=>{e.preventDefault();switchTab('learn');window.scrollTo({top:0})};$('save-experiment').onclick=()=>{$('experiment-name').value=labels[state.tab]+' · '+new Date().toLocaleDateString();$('experiment-notes').value='';$('save-dialog').showModal()};$('confirm-save').onclick=e=>{if(!$('experiment-name').value.trim())return;e.preventDefault();const n={...snapshot(),name:$('experiment-name').value.trim(),notes:$('experiment-notes').value},notes=readNotes();notes.unshift(n);try{localStorage.setItem('jr-geometry-notebook-v1',JSON.stringify(notes));$('save-dialog').close();status('Experiment saved to your notebook on this device.')}catch{download('geometry-experiment.json',JSON.stringify(n,null,2));$('save-dialog').close();status('Device storage is unavailable or full. Your experiment was exported as JSON instead.')}};
switchTab(location.hash.slice(1)||'geometry');
